### ISSUE TITLE
Issues in log causing no response. 

### ISSUE THREAD

**Issue by Travisco29** [Brandawg93/homebridge-nest-cam#105]
i can't seem to find a issue similar to this, but anyway, i am getting this in my log

`[6/24/2020, 5:16:49 PM] [Nest-cam] Error: connect ENETUNREACH 35.201.70.64:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '35.201.70.64',
  port: 443,
  config: {
    url: 'https://webapi.camera.home.nest.com/api/cameras.get_owned_and_member_of_with_properties',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36',
      Referer: 'https://home.nest.com',
      Cookie: 
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'json',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/api/cameras.get_owned_and_member_of_with_properties',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'webapi.camera.home.nest.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/cameras.get_owned_and_member_of_with_properties'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /api/cameras.get_owned_and_member_of_with_properties HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36\r\n' +
        'Referer: https://home.nest.com\r\n' +
        'Cookie: "removed"
        'Host: webapi.camera.home.nest.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      path: '/api/cameras.get_owned_and_member_of_with_properties',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Circular],
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://webapi.camera.home.nest.com/api/cameras.get_owned_and_member_of_with_properties'
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]`

**Comment by Brandawg93** [comment]
[ENETUNREACH](https://www.linuxquestions.org/questions/linux-networking-3/what-exactly-does-error-101-enetunreach-mean-for-a-connect-call-4175612129/) means that homebridge is unable to reach out to the internet. I’m not sure how to help with your specific network issue, but generally, you could try restarting your router and homebridge.

**Comment by Travisco29** [comment]
huh ok. i did just go full ubiquiti gear, so that could be it

**Comment by Brandawg93** [comment]
Ok. If you continue to have issues after checking your network, just reopen this issue.
