### ISSUE TITLE
2 Cameras constantly reset to Default Room

### ISSUE THREAD

**Issue by jw172** [Brandawg93/homebridge-nest-cam#107]
Please help"

Whenever I restart Homebridge, 2 of my 3 Nest Cameras reset to the Default Room in the Home App. Any ideas to solve this?

**Comment by Brandawg93** [comment]
I just noticed that mine are doing the same. Do you restart your homebridge instance often? I've noticed while testing that every so often my cameras disappear and reappear on the next restart. Is that was yours is doing?

**Comment by jw172** [comment]
I'm now no longer sure what causes it - i've just completed 3 restarts to repro the issue and the cameras have remained where they should be and with their correct settings. I'm now wondering if it could be linked to a full restart of my Mac (whcih i'm using as my Homebridge server). What I am sure of is that at least once a day I have to reconfigure 2 cameras in IOS Home (but not my 3rd one). It's also not specific about which type of camera. My Nest Doorbell is one that resets as well as a Nest Outdoor, but my other Nest Outdoor is fine. All on the same Google account.

**Comment by Brandawg93** [comment]
I think the issue is happening [here](https://github.com/Brandawg93/homebridge-nest-cam/blob/master/src/index.ts#L335). For now, I've commented that part out. I've published a test copy if you would like to see if it helps. You can install it via `npm -g i homebridge-nest-cam@test --unsafe-perm`.

**Comment by Brandawg93** [comment]
Actually, I went ahead and released v3.3.0 since I had a few other fixes that needed to go out as well. Try that out for a few days and let me know if your cameras still reset.

**Comment by jw172** [comment]
Appreciate it @Brandawg93 - I'll let you know how it goes :-)

**Comment by Brandawg93** [comment]
I haven't had mine to reset back to the default room yet. If yours resets, feel free to reopen this issue.

**Comment by jw172** [comment]
Thanks @Brandawg93 - all good so far for me too :-)
