### ISSUE TITLE
Bug in latest release?

### ISSUE THREAD

**Issue by sensnowy** [Brandawg93/homebridge-nest-cam#120]
![BBACD062-B97E-453F-920A-2BC6A4917A68](https://user-images.githubusercontent.com/42115708/87021536-a5147e80-c1d5-11ea-8370-1c15607ef341.jpeg)

Getting this issue since last update. Can’t set it to max (3) res anymore either. Somehow it breaks my homebridge. If I load anything but the camera, it’s fine but if I go into a view with the cameras like the summary, all Accessoires stop responding.

**Comment by Brandawg93** [comment]
I've created a new test that may fix this issue. You can install it via `npm -g i homebridge-nest-cam@test --unsafe-perm`. Let me know if this fixes your issue.

**Comment by sensnowy** [comment]
thank you for being so fast. 
i am just installing it.

**Comment by sensnowy** [comment]
dumb question but how do I know if it installed correctly? 
the terminal closed itself. I just rebooted home bridge after a few minutes. 

but right now I was able to set it to 3 again and it does not seem to crash my home bridge anymore. 
no more issues. also the snappiness is back in HomeKit. 

btw the only issue I am getting right now is
[Nest-cam] [NexusStreamer] Connected
[7/9/2020, 14:51:59] [Nest-cam] [NexusStreamer] Redirecting...
[7/9/2020, 14:51:59] [Nest-cam] [NexusStreamer] Connected
[7/9/2020, 14:52:03] [Nest-cam] [NexusStreamer] Disconnected
[7/9/2020, 14:52:17] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)
[7/9/2020, 14:52:37] [Nest-cam] [NexusStreamer] Disconnected
but this was before already. it happens when I open the live feed. 
it is only a few seconds but this is the time for it to connect to it. 
any idea why?

thank you for the help.

**Comment by Brandawg93** [comment]
If you aren't getting the original error, then I think it worked. Try running homebridge in debug mode (`homebridge -D`) and it will tell you what the error is for return audio. Many others are having the same issue. It seems to be port issue.

**Comment by sensnowy** [comment]
ok thanks. gonna leave it running for a day and see if the error occurs again. 
my bad. I thought I had debug running on default but missed it. 
turned it on. 
you want me to open a new thread for it?

**Comment by sensnowy** [comment]
<img width="1071" alt="Bildschirmfoto 2020-07-09 um 15 13 22" src="https://user-images.githubusercontent.com/42115708/87044512-e9644680-c1f6-11ea-8c9f-8a18dbf0f069.png">
<img width="1317" alt="Bildschirmfoto 2020-07-09 um 15 13 53" src="https://user-images.githubusercontent.com/42115708/87044515-ec5f3700-c1f6-11ea-9288-f6b5fd7dda33.png">
ok. running debug mode. HomeKit still crashes and in Homebrdige I can finally see when and how. 

so did it not correctly install the test?

**Comment by Brandawg93** [comment]
It may have not. Try installing it again.

**Comment by sensnowy** [comment]
nope it never installed until now. 
it clearly states test version right now.
let me test everything out.

**Comment by sensnowy** [comment]
keeps on crashing every time I open the nest cam. 
now reducing back to quality (2) instead of (3)
sadly it just crashes without error codes. 
not even in debug mode any info right now. 

crash happened 3 times already.

**Comment by Brandawg93** [comment]
Is it the same write_after_end error?

**Comment by sensnowy** [comment]
no error code even. that is the problem. 

I put it back to (2) and everything is more or less fine. 
sure the audio error pops up from here and there but that is it. 

i am putting it into (3) again for an hour and test on multiple devices. 

will report back.

**Comment by sensnowy** [comment]
so it stopped crashing. 
but somehow my Homebridge keeps on giving "no response" on other devices as if it crashes and reboots. 
after 40 secs everything is back up.
 but now crash report or error message. 
but also the nest cam is suddenly no longer smooth. 
i am gonna blame that on nest itself. 
<img width="779" alt="Bildschirmfoto 2020-07-09 um 16 06 32" src="https://user-images.githubusercontent.com/42115708/87050204-3ef02180-c1fe-11ea-8a52-40dcdb35297a.png">
<img width="1163" alt="Bildschirmfoto 2020-07-09 um 16 06 43" src="https://user-images.githubusercontent.com/42115708/87050210-41527b80-c1fe-11ea-9f42-7dcb8450dd10.png">

**Comment by sensnowy** [comment]
this is the only way for me to show what happens in the app. cannot upload video here. 

https://share.icloud.com/photos/0H_he9GahbvPDqJrKb2AeoklA

**Comment by sensnowy** [comment]
hope it is visible right before the crash how chunky the footage is.
again I am sorry for disturbing you.

**Comment by Brandawg93** [comment]
No problem. The quality is due to Nest. If you are still having issues, usually it's because of port issues. homebridge is streaming the nest plugin correctly, but something (i.e. a router or firewall) is not letting your iphone receive the stream.

**Comment by sensnowy** [comment]
so you are saying the issue with devices being unable to respond is cause of my router blocking them/checking too long ? 
if that is it, then I can just quickly fix it on my end. 
thank you. those lines of code look so damn confusing for me right now. sorry.

**Comment by Brandawg93** [comment]
The lines you sent look like info for another plugin (Sileno City).

**Comment by sensnowy** [comment]
still crashing every time I open the nest cam. 
i deleted the other plugin 
and opened the port on my router for Homebridge
but it just keeps on crashing with no error code every time I open the nest view. 
everything works fine until the moment I open up a. stream. 
i am deleting now almost all other plug ins since they are easy to rebuild. 

any other idea why this is caused?

**Comment by Brandawg93** [comment]
When submitting an issue, I have a few questions listed at the bottom. Would you mind answering those and posting them here?

**Comment by black01gt** [comment]
I have been having a similar issue. By any chance are you running the IOS 14 Beta?

**Comment by sensnowy** [comment]
Basic info: 
MacBook Pro 
iPhone XS
iPad Pro 2018

homekit server is Apple TV 4K with the iPad Pro 2018 

last update that worked with no issues, was the one before this or on setting (2)

cameras in use:
nest hello
nest iq outdoor (biggest issue)

all devices run on current released iOS. no outdated or beta software except test version of nest cam. 


I don't mind deleting all of the Homebridge. right now I deleted all of the plugins that might have caused any issues.

**Comment by sensnowy** [comment]
> I have been having a similar issue. By any chance are you running the IOS 14 Beta?

if you do, try out the test version that is on the very top

**Comment by Brandawg93** [comment]
What is homebridge running on?

**Comment by sensnowy** [comment]
<img width="675" alt="Bildschirmfoto 2020-07-09 um 19 52 36" src="https://user-images.githubusercontent.com/42115708/87073482-c436fe80-c21d-11ea-8065-39a9bb297e16.png">


so I did this all, and in the end, it always bugs out when I open the feed of the nest iq outdoor. 
but right now it runs smooth without the gardena plugins. 

the Homebridge is running on Raspberry 1373331 Pi 3 Modell B+ Mainboard, 1 GB

and here is the software I use to handle it all. 

<img width="1779" alt="Bildschirmfoto 2020-07-09 um 19 54 02" src="https://user-images.githubusercontent.com/42115708/87073608-f47e9d00-c21d-11ea-8bdb-f68a48f69904.png">

**Comment by sensnowy** [comment]
and this is everything else between trying to connect to the live feed until it worked and then stopping the feed

[7/9/2020, 19:53:55] [Config] Terminal session ended.
[1594317235391] INFO  (651 on homebridge): incoming request
    reqId: 25
    req: {
      "method": "GET",
      "url": "/api/plugins",
      "hostname": "192.168.178.26",
      "remoteAddress": "::ffff:127.0.0.1",
      "remotePort": 51722
    }
[1594317235426] INFO  (651 on homebridge): request completed
    reqId: 25
    res: {
      "statusCode": 200
    }
    responseTime: 33.260806000093
[1594317403418] INFO  (651 on homebridge): incoming request
    reqId: 26
    req: {
      "method": "GET",
      "url": "/",
      "hostname": "192.168.178.26",
      "remoteAddress": "::ffff:127.0.0.1",
      "remotePort": 51828
    }
[1594317403439] INFO  (651 on homebridge): request completed
    reqId: 26
    res: {
      "statusCode": 200
    }
    responseTime: 9.191398999886587
[1594317403556] INFO  (651 on homebridge): incoming request
    reqId: 27
    req: {
      "method": "GET",
      "url": "/api/auth/settings",
      "hostname": "192.168.178.26",
      "remoteAddress": "::ffff:127.0.0.1",
      "remotePort": 51830
    }
[1594317403561] INFO  (651 on homebridge): request completed
    reqId: 27
    res: {
      "statusCode": 200
    }
    responseTime: 4.569919999921694
[1594317403733] INFO  (651 on homebridge): incoming request
    reqId: 28
    req: {
      "method": "GET",
      "url": "/api/server/qrcode.svg",
      "hostname": "192.168.178.26",
      "remoteAddress": "::ffff:127.0.0.1",
      "remotePort": 51848
    }
[1594317403781] INFO  (651 on homebridge): request completed
    reqId: 28
    res: {
      "statusCode": 200
    }
    responseTime: 46.55325599992648
[7/9/2020, 19:56:44] [Config] Starting terminal session
[7/9/2020, 19:56:44] [Nest-cam] [NexusStreamer] Disconnected

**Comment by sensnowy** [comment]
again. I am really sorry if this has nothing to do with your amazing plug in and I am just a moron. 
that might most likely be it.

**Comment by Brandawg93** [comment]
None of the above logs look to be anything with Nest-cam. It would say `[Nest-cam]` before it if it were. So it works with the gardena plugin?

**Comment by sensnowy** [comment]
no. I just removed them all. and I am trying to redo all the steps that made it crash earlier. even after I removed the plug ins but it works super fine now. 
i have no idea why the nest iq outdoor takes so long or why there is that error message about audio that it gives out. 
thank you for your time! 
you are awesome.

**Comment by sensnowy** [comment]
sorry for reopening it but I wanted to let you know that the issue is the nest iq outdoor 
opening the feed crashes the entire Homebridge 
from connecting to  a whole "the entire system is rebooting"
i am trying to get a video of when it happens. 
this also explains why there are no error messages. 
the entire server gets basically crashes and boots itself up. 
it works fine with the nest hello. 
the homebridge also goes up to 98% of cpu use right before crash. 
would that be an issue with the encoding?

**Comment by sensnowy** [comment]
here is how it looks like after it crashes. 
https://share.icloud.com/photos/0lr18cVm-SiQWJyegrKhtCsXQ

next video is how I cause the crash. 

but it basically is the same. 
i open the iq outdoor, boom. full on crash. as if I plugged out the cord.

**Comment by sensnowy** [comment]
this is why the gardena plugin had issues as well. the crashes caused me to log in too many times and caused my account to get timed out.

**Comment by sensnowy** [comment]
yep. it works fine right now on (2) settings but on (3) it instantly crashes the entire server. 
do you think my homebridge is too weak for it? 
but then again it worked before.

**Comment by sensnowy** [comment]
i am keeping this thread open for a while until I find more info or am able to push an error code somehow

**Comment by sensnowy** [comment]
I just want to scream. 
I can not longer get it to crash. 
but I promise if I close this thread, it will crash the instant I open the outdoor cam.

**Comment by sensnowy** [comment]
[7/10/2020, 05:44:33] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:44:33] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:44:53] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:44:53] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:45:13] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:45:13] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:45:33] [TadoPlatform] 5 - Error getting state from API.
[7/10/2020, 05:45:34] [TadoPlatform] 6 - Error getting state from API.
[7/10/2020, 05:45:45] [TadoPlatform] 7 - Error getting state from API.
[7/10/2020, 05:45:45] [Nest-cam] Error: getaddrinfo EAI_AGAIN webapi.camera.home.nest.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'webapi.camera.home.nest.com',
  config: {
    url: 'https://webapi.camera.home.nest.com/api/cameras.get_owned_and_member_of_with_properties',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36',
      Referer: 'https://home.nest.com',
      Cookie: 'user_token=g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJuZXN0X2lkOm5lc3QtcGhvZW5peC1wcm9kOjE5ODEzMjU0Iiwic2NwIjpbXSwiaXNzIjoibmVzdC1zZWN1cml0eS1hdXRocHJveHlAbmVzdC1zZWN1cml0eS1hdXRocHJveHkuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJwb2wiOiJhdXRocHJveHktb2F1dGgtcG9saWN5IiwiZXhwIjoxNTk0MzU0NDE0LCJ1dG9rIjoiXHUwMDAwXcOjYlbCrUc8SFx1MDAxNVcnU8K1w7nCtVLDqUs2OnJNTVxuXHUwMDlBVMKzw6vDqkBcdTAwOThnXHUwMDlCw4NcdTAwMDMjwqxzPFB0w63Colx1MDA5RFx1MDA4M8OfXHUwMDFGZ8Kkw6zDuGwqRU5cdTAwOTVBcnZqPEvColx1MDA4NkhcdTAwODhXw4BcdTAwOTnDucOtw6Qmw7F6Qm9cdTAwMULDocO6w7zDocOcXHUwMDE1XHUwMDExwrl2w6ZcdTAwMELDhcOKXC_DkUjDmcOKwqczXHUwMDBCwqUtODTCtlx1MDA5N3bCo8OzXHUwMDBFwrpgYlx1MDA5NXJ5wq51ccOTw5dcdTAwMTRcdTAwMDdSKVx1MDA5OCDCqsO2XHUwMDBFw7JFw6BKwqVcdTAwMTHDoU9cdTAwMUHDjsKtw7NcdTAwOUbDhcOIP8ORYMOkXHUwMDExw77CvVx1MDA4OMOPOcKrw7LDqDDCpFxuwq5cdTAwMTEmMsODXHUwMDAzIcOfR1x1MDAxRXPCpcOvSVx1MDA5MiRcdTAwMTLDk8O6XHUwMDA3wqh9w7pfw7PDrsKxw41cdTAwOTbDoFx1MDA5NMKhXHUwMDA0w5N2ZsO0JcOlelx1MDAwRcK5fj1cdTAwOTDDv0lFXHUwMDg4IiwidXRva3QiOiJHT09HTEVfT0FVVEgifQ.XulCPwtmBATe6gAKYf29CN_zteSN-jQxxVvmS3zzRJFiaf8l_2xL222yEPA6a_oi7UDiEq1vtG7Bmxmv25wL6DvZi11IT49NSz_TASbpASmZHMj0R3mgjRP7X1rU86UO8WK44GdXQNhr6aMI4ClT9qjR5sNdqVSZ_njJBArwulTRN5AM3QfBJe2EAd1QerCk6J5bywfpR_yfA6617nhK9nd1wI4XDFkLmmxB7EHI5DpO2uSY31hv6zOHy3AFYHEiwXYXBxhAFuQCjc-PdVypsKVC0wSxhwxDH2VrQghB3l4FHYnpQA85brxt9UjTLBk4gysi_eoi2JVGbCohGfm1WA'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'json',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/api/cameras.get_owned_and_member_of_with_properties',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'webapi.camera.home.nest.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/cameras.get_owned_and_member_of_with_properties'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /api/cameras.get_owned_and_member_of_with_properties HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36\r\n' +
        'Referer: https://home.nest.com\r\n' +
        'Cookie: user_token=g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJuZXN0X2lkOm5lc3QtcGhvZW5peC1wcm9kOjE5ODEzMjU0Iiwic2NwIjpbXSwiaXNzIjoibmVzdC1zZWN1cml0eS1hdXRocHJveHlAbmVzdC1zZWN1cml0eS1hdXRocHJveHkuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJwb2wiOiJhdXRocHJveHktb2F1dGgtcG9saWN5IiwiZXhwIjoxNTk0MzU0NDE0LCJ1dG9rIjoiXHUwMDAwXcOjYlbCrUc8SFx1MDAxNVcnU8K1w7nCtVLDqUs2OnJNTVxuXHUwMDlBVMKzw6vDqkBcdTAwOThnXHUwMDlCw4NcdTAwMDMjwqxzPFB0w63Colx1MDA5RFx1MDA4M8OfXHUwMDFGZ8Kkw6zDuGwqRU5cdTAwOTVBcnZqPEvColx1MDA4NkhcdTAwODhXw4BcdTAwOTnDucOtw6Qmw7F6Qm9cdTAwMULDocO6w7zDocOcXHUwMDE1XHUwMDExwrl2w6ZcdTAwMELDhcOKXC_DkUjDmcOKwqczXHUwMDBCwqUtODTCtlx1MDA5N3bCo8OzXHUwMDBFwrpgYlx1MDA5NXJ5wq51ccOTw5dcdTAwMTRcdTAwMDdSKVx1MDA5OCDCqsO2XHUwMDBFw7JFw6BKwqVcdTAwMTHDoU9cdTAwMUHDjsKtw7NcdTAwOUbDhcOIP8ORYMOkXHUwMDExw77CvVx1MDA4OMOPOcKrw7LDqDDCpFxuwq5cdTAwMTEmMsODXHUwMDAzIcOfR1x1MDAxRXPCpcOvSVx1MDA5MiRcdTAwMTLDk8O6XHUwMDA3wqh9w7pfw7PDrsKxw41cdTAwOTbDoFx1MDA5NMKhXHUwMDA0w5N2ZsO0JcOlelx1MDAwRcK5fj1cdTAwOTDDv0lFXHUwMDg4IiwidXRva3QiOiJHT09HTEVfT0FVVEgifQ.XulCPwtmBATe6gAKYf29CN_zteSN-jQxxVvmS3zzRJFiaf8l_2xL222yEPA6a_oi7UDiEq1vtG7Bmxmv25wL6DvZi11IT49NSz_TASbpASmZHMj0R3mgjRP7X1rU86UO8WK44GdXQNhr6aMI4ClT9qjR5sNdqVSZ_njJBArwulTRN5AM3QfBJe2EAd1QerCk6J5bywfpR_yfA6617nhK9nd1wI4XDFkLmmxB7EHI5DpO2uSY31hv6zOHy3AFYHEiwXYXBxhAFuQCjc-PdVypsKVC0wSxhwxDH2VrQghB3l4FHYnpQA85brxt9UjTLBk4gysi_eoi2JVGbCohGfm1WA\r\n' +
        'Host: webapi.camera.home.nest.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/cameras.get_owned_and_member_of_with_properties',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://webapi.camera.home.nest.com/api/cameras.get_owned_and_member_of_with_properties',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}
[7/10/2020, 05:45:55] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:45:55] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:46:07] [Nest] Nest API call to subscribe to device settings updates returned an error: EAI_AGAIN
[7/10/2020, 05:46:07] [Nest] Retrying in 10 seconds.
[7/10/2020, 05:46:07] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:46:17] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:46:17] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:46:27] [Nest-cam] Error checking alerts: EAI_AGAIN
[7/10/2020, 05:46:27] [Nest-cam] Error checking alerts: EAI_AGAIN

**Comment by Brandawg93** [comment]
https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes

That is a DNS issue.

**Comment by sensnowy** [comment]
thank you for your help
no more crashes btw. 
the test works fine. 
thank you for your time and sorry for my questions
and thank you for your hard work

**Comment by Prakkie** [comment]
I am using archlinux and video streaming doesnt work when open the cam. I get below error:

[RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)

Please advise.
