### ISSUE TITLE
Nest accounts support

### ISSUE THREAD

**Issue by bogdanbun** [Brandawg93/homebridge-nest-cam#14]
Are Nest accounts still supported? Or migration to Google account would be required?

**Comment by Brandawg93** [comment]
Migration to Google would be required for this. I have no way of testing the old Nest accounts because I only have a Google account.

**Comment by bogdanbun** [comment]
I'd like to say that I migrated to Google account and got the homebridge-nest-cam2 working. Thanks for your work!

**Comment by gitcloneguy** [comment]
it would be nice if it just asks for a token

**Comment by Brandawg93** [comment]
I'm going to close this now, but leave it pinned for future viewers.

**Comment by RobbinHabermehl** [comment]
Unfortunately @Brandawg93, if you're using a Google account that's part of [G Suite](https://gsuite.google.com) it's not possible to migrate your Nest account to a Google account. Do you think there's an efficient way to make this work just like [`homebridge-nest`](https://github.com/chrisjshull/homebridge-nest/blob/master/lib/nest-connection.js#L224) does? I'd be happy to help with this.

**Comment by Brandawg93** [comment]
@RobbinHabermehl I would recommend creating another google account and adding it as a "family member" to your Nest home. That way you can still have the GSuite account with the plugin.

**Comment by RobbinHabermehl** [comment]
That's not working either @Brandawg93, it's required to migrate the account before that can be done.

![image](https://user-images.githubusercontent.com/1640272/92523902-73de1c00-f221-11ea-9797-1318de30498b.png)
