### ISSUE TITLE
login.js doesn't work on RPI due to puppeteer bug

### ISSUE THREAD

**Issue by demonbane** [Brandawg93/homebridge-nest-cam#143]
`node dist/login.js` fails on a Raspberry Pi 4 with a `Syntax error: "(" unexpected` error. I was able to track it down to puppeteer/puppeteer#550. Manually editing `login.js` with the fix [mentioned in the comments](https://github.com/puppeteer/puppeteer/issues/550#issuecomment-635718872) fixed the issue for me. I can't submit a PR since this needs some more logic to be safe I'm sure, but the simple fix for me was changing line 71 in login.js from:

```
const browser = await puppeteer_extra_1.default.launch({ headless: headless });
```
to
```
const browser = await puppeteer_extra_1.default.launch({ headless: headless, executablePath: 'chromium-browser' });
```

I believe this corresponds to https://github.com/Brandawg93/homebridge-nest-cam/blob/77b9514a8e2c930dfc5def2f8cabd914d3ba20aa/src/login.ts#L50

With this (and running with the `-h` flag since I use 2FA, it worked just fine!

**Comment by Brandawg93** [comment]
I've added a `-p` flag to the login function that will allow you to specify the executable path. It will be available in the next release. If you would like to try it, you can install it via `npm -g i homebridge-nest-cam@test --unsafe-perm`

**Comment by Brandawg93** [comment]
This should be fixed in v4.0.0. Feel free to reopen this issue if that's not the case.

**Comment by brn2prgrm** [comment]
I'm having issues passing the -h and -p flag to the login tool at the same time. I have 2FA on my Google account, and it loads Chromium when I specify my path with -p. But when I add the -h flag it seems to ignore the -p.

$ node dist/login.js -h -p /usr/bin/chromium
Unable to open chromium browser. Install chromium manually and specify its path using the "-p" flag.

**Comment by Brandawg93** [comment]
@brn2prgrm It's picking up the `-p` flag but unable to open the file specified. I've changed the error message to reflect this and it will be available in the next release.

**Comment by brn2prgrm** [comment]
But when I run it with just the -P flag it runs Chromium and asks for user/pass, but then stalls out before giving me the token info. If I add the -h flag, since I have 2FA, it doesn't run Chromium.

**Comment by Brandawg93** [comment]
What are you running it on? It could be that chromium doesn't have a GUI to use. I was able to run a few tests and confirm that both `-p` and `-h` work together.

**Comment by squiidz** [comment]
same problem here.
```
(node:7784) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at /usr/local/lib/node_modules/homebridge-nest-cam/dist/login.js:173:50
    at /usr/local/lib/node_modules/homebridge-nest-cam/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/homebridge-nest-cam/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:47:43)
    at Page.emit (/usr/local/lib/node_modules/homebridge-nest-cam/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at /usr/local/lib/node_modules/homebridge-nest-cam/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:166:101
    at /usr/local/lib/node_modules/homebridge-nest-cam/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/homebridge-nest-cam/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:47:43)
    at NetworkManager.emit (/usr/local/lib/node_modules/homebridge-nest-cam/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
(node:7784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Brandawg93** [comment]
@squiidz That is a completely different issue. It seems that your login attempt is not capturing a value correctly.

**Comment by demonbane** [comment]
@brn2prgrm I was having the same misleading error when trying to run it without `DISPLAY` set. Make sure your terminal can launch X apps from the command line and then try again?

**Comment by brn2prgrm** [comment]
Ok, maybe I'm missing something... Do I need a display for login.js to work?  I am currently running everything off of a headless rPi4

**Comment by demonbane** [comment]
`login.js` works from a console for "regular" logins, but If you're using 2FA on your google account, then yes you have to have a display. I'm running on a RPI4 as well, and just using xrdp to provide a virtual desktop that I can remote into for things like this.

**Comment by brn2prgrm** [comment]
When I run login.js from the homebridge-nest-cam folder, and only use the -P flag, it prompts for user/pass, but then hangs on 'Finishing Up' until I force close the script.
<img width="847" alt="image" src="https://user-images.githubusercontent.com/21067957/90573291-b7da8580-e17b-11ea-90ee-3cd35ab3d919.png">

When I add the -H flag, since my Google account has 2FA, it gives the unknown path error.  It seems like it's not passing the -P flag to the script...
<img width="847" alt="image" src="https://user-images.githubusercontent.com/21067957/90573318-c88afb80-e17b-11ea-9d8e-d2f705658be3.png">

**Comment by brn2prgrm** [comment]
> `login.js` works from a console for "regular" logins, but If you're using 2FA on your google account, then yes you have to have a display. I'm running on a RPI4 as well, and just using xrdp to provide a virtual desktop that I can remote into for things like this.

Ok, that sucks, but thanks for the confirmation!
