### ISSUE TITLE
No Motion Sensor Accessories For Cameras

### ISSUE THREAD

**Issue by SlothTheHero** [Brandawg93/homebridge-nest-cam#148]
**Describe the bug**

No motion sensor accessories are showing up, this kills the option to get motion alerts from your cameras in the Home app.

**To Reproduce**

Nothing to reproduce, on going behavior. I installed and put in the google auth like the instructions said.

**Expected behavior**

There should be a motion sensor accessory that will activate notifications for motion on that camera.

Please answer these questions before submitting this issue:
```
On what OS are you running homebridge: The Raspberry Pi image
What camera types are having issues: 2 Outdoor Google Nest Cameras and a Nest Hello
Does this issue occur consistently or randomly: Consistently
If applicable, what was the last version that worked properly: N/A
```

**Comment by Brandawg93** [comment]
This should be fixed in v4.0.0. Feel free to reopen this issue if that's not the case.
