### ISSUE TITLE
'Alert Type' of 'None' results in many motion sensors

### ISSUE THREAD

**Issue by jw172** [Brandawg93/homebridge-nest-cam#165]
With the introduction of the 'Alert Type', when I set this to 'None', a further 13 motion sensors (20 in total) appear for my 3 Nest cameras - for face detection, etc.

When I set this to 'Motion', 7 motion sensors appear in total.

Maybe I'm not setting the 'Alert Type' correctly, but I would expect 'None' to show fewer sensors than 'Motion', not the other way around.

Please help.

**Comment by Brandawg93** [comment]
Are you trying to remove all the sensors? What happens if you set `motionDetection` to false?

**Comment by jw172** [comment]
I was happy with having 'motion detection' only but without Alerts (as these are managed through my Nest Aware subs). When I set motionDetection to false all the Motion Sensors are removed, but I don't think this gets me back to where I was before this latest version. Maybe this is all down to my lack of undestadning of how the new alert functionality works?

**Comment by Brandawg93** [comment]
I do see an issue in the code with the `alertTypes` that I'm looking into now. The new alert functionality simply allows you to specify which type of events you would like to have sensors for. They aren't specifically for notifications. They can also be used for automations as well. Which types are you trying to remove?

**Comment by jw172** [comment]
I was trying to remove 'sound' and 'people' events and keep just 'motion', or remove 'sound' and 'motion' events and keep just 'people' but this doesn't currently seem possible. Note I am using IOS 14 Beta, so not sure if this has an impact.

**Comment by Brandawg93** [comment]
I've published a new test that should hopefully fix this. You can install it via `npm -g i homebridge-nest-cam@test --unsafe-perm`. Let me know if this works for you.

**Comment by jw172** [comment]
Awesome job Brandon - works for me :-)

**Comment by Brandawg93** [comment]
Great! You can run the test for now if you want and I'll release this fix in the next official version.

**Comment by Brandawg93** [comment]
This is in v4.2.0.
