### ISSUE TITLE
'Face' Sensors not showing up for IQ Cameras

### ISSUE THREAD

**Issue by brn2prgrm** [Brandawg93/homebridge-nest-cam#170]
BUG: After enabling 'Face' detection, my Hello Doorbell shows the sensors, but my IQ Outdoor and IQ Indoor cameras do not have 'Face' sensors.  Nest Hub Max's also do not have appropriate sensors.

On what OS are you running homebridge: Raspberry Pi4b
On what iOS version are you having issues: iOS 14 Developer Beta
What camera types are having issues: IQ Indoor, IQ Outdoor
Does this issue occur consistently or randomly:  Consistently
If applicable, what was the last version that worked properly: N/A

Motion debug data is attached...

[Motion Debug.txt](https://github.com/Brandawg93/homebridge-nest-cam/files/5023545/Motion.Debug.txt)

**Comment by brn2prgrm** [comment]
Debug Data:

[Motion Debug.txt](https://github.com/Brandawg93/homebridge-nest-cam/files/5023543/Motion.Debug.txt)

**Comment by Brandawg93** [comment]
The issue was that I was manipulating the same array for all cameras, so when I removed face detection from one, it would remove it from the rest. The motion arrays are now camera dependent. This should be fixed in the latest test version.

**Comment by Brandawg93** [comment]
Fixed in v4.3.0.
