### ISSUE TITLE
Switches as Custom Bool Characteristics

### ISSUE THREAD

**Issue by lukescott** [Brandawg93/homebridge-nest-cam#179]
I realize there are settings to turn off switches completely, such as:

```
doorbellSwitch
streamingSwitch
chimeSwitch
audioSwitch
```

It would be nice if there was a setting to expose these as a custom boolean characteristic instead of a switch.

This would keep the Apple Home app nice and clean (which won't constantly show "4 switches on" on the main screen), but still keep the switches accessible apps such as Home+, which does a great job of supporting custom characteristics.

**Comment by Brandawg93** [comment]
You can hide the switches in the config options. https://github.com/Brandawg93/homebridge-nest-cam#options

**Comment by lukescott** [comment]
Characteristics in the HomeKit protocol are very extendable. You can create your own and it works just fine. The downside is Apple's built-in Home app doesn't understand them, so they won't show up. However, custom apps on the app store like [Home+](https://apps.apple.com/us/app/home-4/id995994352) can expose those characteristics. With a Bool type, a toggle switch. With a Number, a slider, etc.

Here's the `On` characteristic in `HAP-NodeJS`:

```typescript
export class On extends Characteristic {

  static readonly UUID: string = '00000025-0000-1000-8000-0026BB765291';

  constructor() {
    super('On', On.UUID);
    this.setProps({
      format: Formats.BOOL,
      perms: [Perms.READ, Perms.WRITE, Perms.NOTIFY]
    });
    this.value = this.getDefaultValue();
  }
}

Characteristic.On = On;
```

You could make your own, such as:

```typescript
export class StreamingEnabled extends Characteristic {

  static readonly UUID: string = 'A79FF0D2-A5F6-46E0-8F75-45A0FA3611D9'; // randomly generated; unique

  constructor() {
    super('StreamingEnabled', StreamingEnabled.UUID);
    this.setProps({
      format: Formats.BOOL,
      perms: [Perms.READ, Perms.WRITE, Perms.NOTIFY]
    });
    this.value = this.getDefaultValue();
  }
}
```

Then you use `addCharacteristic` like it was an optional characteristic. Homebridge/HAP-NodeJS warns it doesn't know what your uuid is on startup, but it work fine.

Here's my door lock in Home+ where I added "Vacation Mode" to disable key codes on my Z-Wave lock:

![IMG_2528](https://user-images.githubusercontent.com/486224/90069152-bce49400-dca6-11ea-82d3-cbadbb2dfb76.PNG)

What's nice about making this a custom characteristic is you can do things like "Siri, turn off everything" and she won't mess with your configuration switches. If I want to involve configuration in automations I can still set them up in Home+.

**Comment by Brandawg93** [comment]
This is really good information! I'll definitely look more into this. For now, I'm going to leave it out since it would throw a warning that the majority of users would see, and I have no way of testing it personally. But I really like the concept. I wish this was built into the Home app by default.

**Comment by Brandawg93** [comment]
I'm going to close this for now since I can't add it in until Homekit officially supports things like this, but I will keep this on my future todos. Thanks again for the info!
