### ISSUE TITLE
Long Polling

### ISSUE THREAD

**Issue by lukescott** [Brandawg93/homebridge-nest-cam#181]
It seems like there is an api method (private?) that allows for long polling on home.nest.com. This still appears to work since I migrated my Nest account. homebridge-nest also makes use of it:

https://github.com/chrisjshull/homebridge-nest/blob/744b48474f126060833e5ee97330112f652bc48c/lib/nest-connection.js#L415-L441

Likely will need to subscribe to different object ids than what homebridge-nest is requesting, but this should at the very least let you know when a motion/doorbell event comes in.

**Comment by Brandawg93** [comment]
This is not used for cameras but instead for other devices such as the thermostat. The method I use for polling is the only method currently to check for motion events.

**Comment by Brandawg93** [comment]
I'm going to close this one I can't use the above code for cameras, but if you see any other features from other plugins that you would like to test, feel free to fork this repo and test them out. If they work, you can submit a pull request and I can add it directly into the plugin.
