### ISSUE TITLE
Nest Hello - Removed faces still show as accessories

### ISSUE THREAD

**Issue by MED1975** [Brandawg93/homebridge-nest-cam#186]
Hi.

I recently noticed that an accessory is now created for every identified face - including people that I added through the Nest app a long time ago and will very seldom come to my home. I decided to delete the Nest face history as I am now managing the Nest devices through the Home app. I then restarted Homebridge and expected the face accessories to be removed, but they are all still showing.

Any ideas? I would rather not remove the plugin as I've just managed to get everything set up with automations etc.

Thanks!

**Comment by Brandawg93** [comment]
The previous faces were cached. If you remove the camera from cache (Homebridge Settings) and restart homebridge, they will be removed.

**Comment by MED1975** [comment]
Thank you! I did think removing an item from cache was more destructive but this has worked perfectly.
