### ISSUE TITLE
Nest Hello Notify Through Homepod

### ISSUE THREAD

**Issue by zacksmash** [Brandawg93/homebridge-nest-cam#199]
I'm trying to select the toggles to output the doorbell chime through HomePods, but they will not flip.

1. Go into the Home App
2. Select doorbell cam
3. Tap the gear icon in the video feed
4. Tap Notifications
5. Tap Chime on HomePod
6. Toggle one of the switches to your HomePods.

**Expected behavior**
The switch(es) should toggle allowing the chime to go through the HomePod.

Please answer these questions before submitting this issue:
```
On what OS are you running homebridge: macOS Catalina
On what iOS version are you having issues: iOS 14
What camera types are having issues: Nest Hello
Does this issue occur consistently or randomly: Consistently
If applicable, what was the last version that worked properly: N/A
```

**Comment by Brandawg93** [comment]
I'm going to close this since it is a HomeKit issue on iOS 14. I would assume that when iOS 14 comes out of beta, they will have this resolved.

**Comment by simonrb2000** [comment]
iOS14 has been out a while and whenever I toggle the Chime on HomePod I get a message saying "Could not complete operation" 

Is it still broken or is it my setup?
