### ISSUE TITLE
Google Auth Automated Setup doesn't work

### ISSUE THREAD

**Issue by Oh4sh0** [Brandawg93/homebridge-nest-cam#223]
**Describe the bug**
When trying to login with homebridge-config-ui-x and selecting "Link Account" with my Google Account it always fails and prompts me to perform a manual linking. I had/have previously had it manually configured, but seem to have to manually renew the token monthly, which is a huge pain in the ass.

The error is always:
Could not generate "googleAuth" object. You can still manually retrieve the issue token and enter it below.

**To Reproduce**

1. I can't think of any reason my experience would be special or unique, so I would assume anyone logging in and trying to link their account would have the same experience? I'm also not familiar with any enhanced debugging as part of this process I can do, so if there's anything that can provide additional logging, please let me know.

Please answer these questions before submitting this issue:
```
On what OS are you running homebridge:  macOS 10.15.6
On what iOS version are you having issues: N/A
What camera types are having issues: Nest Hello
Does this issue occur consistently or randomly: Consistent
If applicable, what was the last version that worked properly: Have never used this feature before. 
```

**Comment by Brandawg93** [comment]
> I would assume anyone logging in and trying to link their account would have the same experience?

I've confirmed it's working for some users, but it is hit-or-miss for others. The best way to debug it is to run the process manually. Here are the steps to do that:
1. Start a terminal session in config-ui-x.
2. Navigate to the plugin's root directory (for me, it's `/homebridge/node_modules/homebridge-nest-cam/`)
3. Run `node dist/login.js`

This is the same process that runs when using the UI. If you want, you can copy the output here, and I'll do my best to help.

**Comment by Oh4sh0** [comment]
Thanks @Brandawg93 

.. That led me down a good path. I noticed in that login.js file, it is requiring four variable in order to make the call.
clientId
loginHint
domain
cookies

So, since it was failing, I added log commands to output those values. clientId was returning empty, thus the reason it was not building the auth object. 

Debugging further backward, at the beginning of that file we're defining clientId:
let clientId = '';

to empty, so it isn't null, I'm assuming, but then we're not altering it until:
// Building issueToken
if (!clientId && url.includes('challenge?')) {
   const postData = request.postData().split('&');
   clientId = postData.find((query) => query.includes('client_id=')).slice(10);
}

So, outputting the client ID and url just prior to that gives me a bunch of outputs, as though it is checking every loaded url/resource to see if any include the "challenge?" string, but none of the urls ever do, and thus the clientId is never getting set. 

I'm seeing some odd errors from trying to reach home.nest.com from some browsers on my network at random, including this box, so it is possible the issue is related. From the console:
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://home.nest.com/js/runtime-2329c13971190a4fcf1a.js' with computed SHA-256 integrity 'cxWUiCcVfPSuoYVSmyUuA9mEwBF95lGWwJ37rxInXZA='. The resource has been blocked.

**Comment by Oh4sh0** [comment]
I was able to get the 'https://home.nest.com/' to load one of those times, and logged out, but still never receive a url with the "challenge?" string.

Here's where I'm adding those logs to find the outputs:
```
// Building issueToken
console.log("client id1: " + clientId)
console.log("url: " + url)
if (!clientId && url.includes('challenge?')) {
```

I was thinking maybe it had something to do with enabling 2FA, but after enabling it, I still do not get a url with that challenge string, and furthermore it breaks the process altogether. I did see a client Id in other urls, though. So I was able to modify that code block to look at another url instead--to:

```
if (!clientId && url.includes('CheckCookie?')) {
const postData = url.split('&');
clientId = postData.find((query) => query.includes('client_id=')).slice(10);
}
```

and viola, I can now login fine as it is correctly capturing the clientId. So that begs the question of what that challenge url is, why are some users getting it and other users not, and should that process be using a different url to pull the clientId value from?

**Comment by Brandawg93** [comment]
Wow! Thanks for the info. I'll do some testing just to check mine works as well. I've been pulling my hair out trying to figure out why this works for some users and not for others.

**Comment by Brandawg93** [comment]
The above code worked for me as well. Thanks again for this fix! It is available in v5.1.0.

**Comment by Oh4sh0** [comment]
Sure thing. I'd love to see this feature added to [homebridge-nest](https://www.npmjs.com/package/homebridge-nest) as well if you have any insight on how to do it.

**Comment by Brandawg93** [comment]
It would be up to the developer of the plugin to add it. It hasn't been updated in a while, so I doubt it would be pulled in.

**Comment by Oh4sh0** [comment]
Seeing this issue as back again for myself; No urls that are output contain a clientid string.
