### ISSUE TITLE
What is bug 429

### ISSUE THREAD

**Issue by geoffreyspencer** [Brandawg93/homebridge-nest-cam#226]
Not a feature nor bug request but information request. I frequently get error code 429. It is not in your error code list. What is 429? Thanks.

**Comment by Brandawg93** [comment]
Thanks for the catch. I've added the info to the error codes page.

https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes#429

**Comment by Brandawg93** [comment]
The `429` errors should be a little better in v5.1.0.
