### ISSUE TITLE
Poor Video Quality with Homebridge Rasbian Image

### ISSUE THREAD

**Issue by nscheffer** [Brandawg93/homebridge-nest-cam#234]
Hi,

I am using the Homebridge Raspian image on a Raspberry pi 4 4Go working well with the following plugin :

- Tahoma #dubocr (I got a lot of devices connected to my Tahoma using IO Homecontrol protocol)
- Dummy #nfarina (to switch on when I arrive at home, and opening the gate and garage automatically when I am on my motor bike)
- Nest #chrisjshull (Thermostats and Protect)
- Nest Cam #Brandawg93 (Cam IQ and Hello)

Before I was using the Starling Home Hub with very good video results. Now I would like to have all in one single Raspberry since multiple boxes.

Now using the Nest Cam plugin I found the video quality very poor. Could it be a lack of video hardware acceleration with the Homebridge Raspbian image ?

On the setting there is no path filled by default, may I need to fill it ?
If yes what is the path where we have all FFMPEG Libs ?

Many thanks in advance.
Regards

Nicolas

**Comment by Brandawg93** [comment]
Try using the `copy` codec and let me know if that works for you.

**Comment by jvic1234** [comment]
I have zero problems using libx264 on pi4 with 4gig ram.

pi3 was horrible

**Comment by Brandawg93** [comment]
There isn't much else I can do from the plugin standpoint since it is getting the data from the Nest cam. The only two ideas I can think of are: 
1. Use `copy` as your `"ffmpegCodec"`
2. Play with the `"streamQuality"` settings

**Comment by Brandawg93** [comment]
Also, regarding Starling, I would assume that the box used by Starling is hardware optimized for streaming. That's probably why it seems better.

**Comment by nscheffer** [comment]
Using Homebridge Rasbian image with Homebridge 1.2 Beta 38 seems to be really better on a Raspberry Pi 4 4G !

Is there a way to carry the Nest video stream catch on internet back to home using Homebridge and then be injected into an Homekit device like the iPhone when using Home app to watch the video stream to have the stream untouched with the same quality and settings as the original ?
Or Homekit force to downgrade it before to read it ?
If yes how to do it ?

**Comment by nscheffer** [comment]
the "streamQuality" settings is set to the maximum High.

**Comment by Brandawg93** [comment]
Use the `copy` codec.
