### ISSUE TITLE
homebridge acting up since upgrade

### ISSUE THREAD

**Issue by sensnowy** [Brandawg93/homebridge-nest-cam#237]
<img width="1038" alt="Bildschirmfoto 2020-09-05 um 15 07 09" src="https://user-images.githubusercontent.com/42115708/92305821-00bb7800-ef8b-11ea-95c4-e11c487bc7c4.png">
<img width="1030" alt="Bildschirmfoto 2020-09-05 um 15 07 30" src="https://user-images.githubusercontent.com/42115708/92305824-01eca500-ef8b-11ea-9162-104252fd22a0.png">

switched to a raspberry pi 4 yesterday and for some reason once nest cam see's a person, it crashes all plugins on my end. 
this is what I see right now. it also reported ENETUNREACH. But once I restart it, everything is fine until Nest notices a person. 

the day before everything worked fine on my old raspberry. 
this is a new image btw.
did everything new. 
some hours it just works fine too. 

any idea why? and it is only nest-cam that reports issues. 
all other plugins are fine except once another plug in reported ENETUNREACH as well but then caught itself again until nest-cam said no. 

i am running a pihole on another raspberry. is this the cause for it?

**Comment by Brandawg93** [comment]
It's a known issue. I'll fix it in the next release.

**Comment by sensnowy** [comment]
<img width="1163" alt="Bildschirmfoto 2020-09-05 um 17 35 13" src="https://user-images.githubusercontent.com/42115708/92308493-387feb00-ef9e-11ea-9083-60cb9a34e315.png">


like it works fine even when I access it but after a while it just stops working and I dont know why

**Comment by sensnowy** [comment]
thank you ! sorry to bother. I will close the thing then. 

thank you so much

**Comment by Brandawg93** [comment]
I'll close it when I release the next version so I remember to do this. 😀

**Comment by jvic1234** [comment]
it looks like homebridge 1.1.6 update fixes all these errors

**Comment by jvic1234** [comment]
spoke to soon, the errors are back :)

**Comment by Brandawg93** [comment]
This should be fixed in v5.2.1. Let me know if you still have any issues.
