### ISSUE TITLE
Unable to open chromium. You can still manually retrieve the issue token and enter it below

### ISSUE THREAD

**Issue by nscheffer** [Brandawg93/homebridge-nest-cam#267]
Hi,

Trying to use a Raspberry Pi 4 with Raspi OS 64 Bits (version from August 28) with latest Homebridge 1.2.2 and your plugin but when I try to setup using the easy way I got the following error :
"Unable to open chromium. You can still manually retrieve the issue token and enter it below."

Why ?
Thanks in advance for any help.
Regards,

Nicolas

**Comment by Brandawg93** [comment]
Whoops. That responded automatically. Are you able to install chromium manually?

**Comment by nscheffer** [comment]
Installed when install your plugin : 

pi@homebridge:~ $ dpkg-query -l | grep chromium
ii  chromium                         83.0.4103.116-1~deb10u3             arm64        web browser
ii  chromium-common                  83.0.4103.116-1~deb10u3             arm64        web browser - common resources used by the chromium packages
ii  chromium-sandbox                 83.0.4103.116-1~deb10u3             arm64        web browser - setuid security sandbox for chromium

**Comment by nscheffer** [comment]
I can try to install it again

**Comment by Brandawg93** [comment]
The plugin uses the command `which chromium-browser` to find where it is. If that is empty then that may be the issue.

**Comment by nscheffer** [comment]
Correct !
pi@homebridge:~ $ which chromium-browser
pi@homebridge:~ $

**Comment by Brandawg93** [comment]
It could also be `which chromium`. If you get that to work, you should be good to go.

**Comment by nscheffer** [comment]
I am using Raspi OS 64 bit (not yet available) and I thing it's the problem :
pi@homebridge:~ $ sudo apt install chromium-browser -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 chromium-browser:armhf : Depends: libcups2:armhf (>= 1.4.0) but it is not going to be installed
                          Depends: libgtk-3-0:armhf (>= 3.9.10) but it is not going to be installed
                          Depends: chromium-codecs-ffmpeg-extra:armhf (= 78.0.3904.108-rpt1) but it is not going to be installed or
                                   chromium-codecs-ffmpeg:armhf (= 78.0.3904.108-rpt1) but it is not going to be installed
                          Depends: libraspberrypi0:armhf but it is not going to be installed
                          Recommends: chromium-browser-l10n:armhf but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by nscheffer** [comment]
I am going to revert to official Homebridge image

**Comment by Brandawg93** [comment]
Ok. Let me know if that works for you.

**Comment by nscheffer** [comment]
Did a revert to an official Homebridge Raspbian from scratch and got better result than before but stuck just after filled the password with message " Logging in, please wait...." and wait for ever ...

**Comment by Brandawg93** [comment]
Try using the manual CLI to see where it gets stuck.

**Comment by nscheffer** [comment]
working by doing it manually with Chrome to retrieve needed infos !

**Comment by nscheffer** [comment]
Keep it like this and wait an official Homebridge Raspi OS 64 Bits
