### ISSUE TITLE
can't get this to work on HOOBS 3.2.6

### ISSUE THREAD

**Issue by koweye** [Brandawg93/homebridge-nest-cam#284]
**Describe the bug**
could not get the camera to show up in homekit

**Debug Output**
this what i see in the logs
10/4/2020, 8:22:45 AM [Nest-cam] Create camera - Front Door
10/4/2020, 8:22:45 AM [Nest-cam] Error fetching cameras - undefined

**To Reproduce**

1. 

**Expected behavior**

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: HOOBS
On what iOS version are you having issues: iOS14, ipadOS 14
What camera types are having issues: nest doorbell camera
Does this issue occur consistently or randomly: consistent
If applicable, what was the last version that worked properly: not sure, the previous version
```

**Comment by Brandawg93** [comment]
Personally, I don't run HOOBS and I know that it has been a while since it was updated. I've been updating the plugin with new features from the official Homebridge and am not sure if these features are included in the older HOOBS. I would recommend [migrating to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-to-migrate-from-HOOBS-to-Homebridge) if you can, otherwise, you could try clearing any cache that HOOBS saves.

**Comment by koweye** [comment]
> Personally, I don't run HOOBS and I know that it has been a while since it was updated. I've been updating the plugin with new features from the official Homebridge and am not sure if these features are included in the older HOOBS. I would recommend [migrating to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-to-migrate-from-HOOBS-to-Homebridge) if you can, otherwise, you could try clearing any cache that HOOBS saves.

ok thanks. i just figured the only thing that changed was the plugin so i thought i would ask. i'll just wait and see, maybe others that run hoobs have the same issues or have suggestions.

**Comment by Brandawg93** [comment]
Are you still having issues with the latest version of the plugin? It should be 5.4.1.

**Comment by koweye** [comment]
hello sorry for the late response. after i couldn't get it to work, i
removed the plug in. i guess i first posted before the last update so i
will try and install 5.4.1 and will let you know. thanks for checking

**Comment by koweye** [comment]
ok i re-installed 5.4.1... same error,

10/14/2020, 6:39:05 PM [Nest-cam] Create camera - Front Door10/14/2020,
6:39:05 PM [Nest-cam] Error fetching cameras - undefined

**Comment by Brandawg93** [comment]
> 6:39:05 PM [Nest-cam] Error fetching cameras - undefined

After looking more into this, the errors haven't looked like this since version 3 of the plugin. It seems that you are running a very old version of the plugin.
