### ISSUE TITLE
Chime on HomePod

### ISSUE THREAD

**Issue by simonrb2000** [Brandawg93/homebridge-nest-cam#301]
**Describe the bug**
When trying to enable Chime on HomePod I get Could Not Complete Operation.
**Debug Output**

**To Reproduce**

1. In Home app, select doorbell camera
2. Click Notifications
3. Select Chime on HomePod

**Expected behavior**
HomePod should Chime

I noticed this was mentioned back in August and I did comment there however that is a Closed issue. It stated this should be sorted once iOS 14 is out of Beta. As iOS 14 is out of Beta and I am still not able to enable Chime on HomePod I’m just checking if its an issue with the plugin, Apple or my setup. 

Thank you

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: Raspberry Pi
On what iOS version are you having issues: 14.0.1
What camera types are having issues: Nest Doorbell
Does this issue occur consistently or randomly: Consistently
If applicable, what was the last version that worked properly: Never worked
```

**Comment by Brandawg93** [comment]
Could you post the debug output of homebridge when the issue arises. Hopefully, it throws an error so I can see where it happens.

**Comment by OttoVonSkidmark** [comment]
Same behavior on my setup (through Starling)

**Comment by Brandawg93** [comment]
@OttoVonSkidmark Good to know. If it's happening with Starling, then it's definitely a Homekit issue as I'm sure the Starling team would have a quick fix for it if it were plugin related.

**Comment by simonrb2000** [comment]
With iOS 14.1 Chime on iPad is working now. Turns out it was Apple even with iOS 14. Thanks all

**Comment by OttoVonSkidmark** [comment]
I no longer get the error message on 14.1 on HomePod.  Noe I just need to have someone ring the doorbell :)

**Comment by simonrb2000** [comment]
> I no longer get the error message on 14.1 on HomePod. Noe I just need to have someone ring the doorbell :)

I rang our doorbell 🤣
