### ISSUE TITLE
Plugin doing a TON of DNS queries

### ISSUE THREAD

**Issue by vmstan** [Brandawg93/homebridge-nest-cam#313]
I have homebridge-nest-cam running in a Docker instance of Homebridge. Latest versions of all modules, and v12.19.0 of Node.JS. The plugin is doing a ton of DNS queries, at least once every 4-6 seconds. I have two Pi-hole instances on my network, and they are both absolutely slammed with queries to nexusapi-us1.camera.home.nest.com

<img width="480" alt="CleanShot 2020-10-20 at 13 04 50@2x" src="https://user-images.githubusercontent.com/3002053/96626537-3ca96300-12d5-11eb-9d19-c84440d717f9.png">

This is without ever having the cameras even visible in a Home app on any Apple device. They have a combined total of about 120,000 lookups every day, just for this one instance. My Pi-hole's cache this and return it, so it's not a "problem" except for that my DNS logs are just full of this stuff.

I just recently switched to running Homebridge in Docker as opposed to native installs, and I do notice that my other instance also does a fair number of queries (from the myQ and general Nest plugin) so it might be partially blamed on the Docker container/host OS not caching these lookups at the OS level, but even still that one maybe only 1/5 combined of what the Nest Cam plugin is generating.

Any idea how to reduce these queries?

**Comment by Brandawg93** [comment]
This is expected behavior. The plugin needs to check for motion on an interval to be able to send notifications. You can change the interval in your [config options](https://github.com/Brandawg93/homebridge-nest-cam#options) if you want to reduce the number of queries. Just know that motion detection will not work as quickly.

**Comment by vmstan** [comment]
Interesting. The only camera that I ever need alerts for is the doorbell, and I usually get those through the Nest app anyway, so I will likely just disable all the alerting. If I increase the polling interval to 60 seconds, and disable all of the alerts, will this impact any of the status updates when you open the Home app (seeing if the various camera switches and such are active?)

**Comment by Brandawg93** [comment]
The switches and statuses update only when you open the Home app or change a camera within the Nest app. If you want to disable motion detection altogether, you can set `motionDetection` to false which will never initialize the interval timer.

**Comment by vmstan** [comment]
OK, I disabled all those and the Pi-hole logs seemed to have calmed down. Thanks.

**Comment by Brandawg93** [comment]
Good to hear!
