### ISSUE TITLE
Nest Hello in 2 different houses under same account

### ISSUE THREAD

**Issue by jamesngob** [Brandawg93/homebridge-nest-cam#335]
Hi everyone,
I have 3 x Nest Hello installed in 2 different physical locations. These 2 locations each added as a "house" in the Nest goolge account. So in this account, I have 2 "house" (or they called it structure)
I sucessfully added the Nest-Cam plugin to homebridge. Up to before the Homebridge UX update this morning, I was able to see all 3 camera in my Homekit
After the Homebridge UX update, now I can only see 2 cameras, which belong to 1st location only, in the homekit. The other camera in the 2nd location does not show in the homekit
Am I missing anything after the update? How do I add the 3rd camera on the 2nd location to my Homekit as it was before?
Thank you

**Comment by Brandawg93** [comment]
If you downgrade does it work again? If not, try clearing your homebridge accessory cache.

**Comment by jamesngob** [comment]
Hi Brandawg93,
I have not downgraded but I would like to clear the homebridge accessory cache. How do I go about doing it?
Thank you very much

**Comment by Brandawg93** [comment]
In homebridge-config-ui, click homebridge settings then accessory cache.

**Comment by jamesngob** [comment]
Clean the cache did do the trick. My 3rd camera is now back to my Homekit. Thank you very much

But talking about the "multi house" function, may I request if you can add the new features in which, you will allow people to add the Nest camera or Nest hello from each location specifically if they also have "multi house" feature enabled on their Homekit?
For example, if I have one Homekit account, but under that account, I have created 2 "homes": Home A and B
And in Nest Google account, I also created 2 "houses": House A and B.
If I am selecting Home A from Homekit, then nest Camera or Nest Hello in House A will show up in the Homekit - Home A, and vice-versa, if I select Home B from Homekiet, then Nest cam or Nest hello in House B will show up...
Is this something possible?
Thank you

**Comment by Brandawg93** [comment]
This is already available. You would need to run 2 instances of homebridge and homebridge-nest-cam and filter the structures via the `structures` option.

**Comment by jamesngob** [comment]
Oh I see what you mean... Thank you again very much
Cheers
