### ISSUE TITLE
Person sensors not firing correctly when camera has multiple zones

### ISSUE THREAD

**Issue by cscott365** [Brandawg93/homebridge-nest-cam#347]
The Person sensor does not fire for Nest cameras with multiple zones unless ALL zones in the camera fire for a person. I have my front yard and back yard cameras split into zones and the person alert for the camera only fires if you walk into all of the zones instead of just one. You get a motion alert on the zone, but there is no person alert for the zone it appears to only be at the camera level.

1. Setup multiple zones for a single camera in the Nest application and set them for Person alerts
2. Have a person enter into only one of the zones and Nest will alert for a Person in that zone
3. Zone trigger happens in Homebridge (not a person alert), but the Person sensor in Homebridge for the Camera as a whole does not trigger

**Expected behavior**
If a person enters any zone, the overall Person sensor for the camera should fire in Homebridge and trigger in Homekit, or add a Person trigger for each Zone as part of the system. 

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: Windows 10 Computer with Node.js 14.15 as a service and Homebridge 1.2.3
On what iOS version are you having issues: 14.1
What camera types are having issues: Nest Cam IQ Outdoor
Does this issue occur consistently or randomly: Consistently
If applicable, what was the last version that worked properly: None
```

**Comment by Brandawg93** [comment]
With the current setup of the plugin, you cannot specify alert types for specific zones. I haven't found an intuitive way to do this yet. Currently, if you receive a person alert or a zone alert, you receive a notification. They are not dependent upon each other. Here is an example of what the alert looks like from Nest:

```
{
   "playback_time":1604339923368,
   "start_time":1604339923368,
   "camera_uuid":"REDACTED",
   "face_id":"",
   "is_important":false,
   "face_category":"UNSET",
   "end_time":1604339933421,
   "importance":0,
   "face_name":"",
   "in_progress":false,
   "id":"REDACTED",
   "zone_ids":[
      "123",
      "456"
   ],
   "types":[
      "motion",
      "person",
      "sound"
   ]
}
```
It simply checks if anything within that lines up with your homebridge settings and if so, sends a notification. What you are probably experiencing is a delay of the notification being sent. By default, the plugin checks for motion every 10 seconds. You can increase that value in the settings if you like.

**Comment by cscott365** [comment]
I have run quite a few tests, and the Person alert from this plugin only fires if ALL zones have some form of alert and include a person detection. If there is a single zone that does not fire, the Person alert will not fire even though the Nest Person alert fires for a zone. I would just like the Person alert to fire if a Person is detected in any zone. I can confirm that this is NOT a delay on notification.

**Comment by Brandawg93** [comment]
You can view the code [here](https://github.com/Brandawg93/homebridge-nest-cam/blob/master/src/nest/cam.ts#L160). The plugin simply creates a list of notification types and triggers them all. It could be that Nest is only sending the "person" type once a person is seen in all zones. The plugin is only working with the data provided by Nest. You could try looking at the network calls on the Nest website to see if you are receiving "person" type alerts when you expect to.

**Comment by cscott365** [comment]
As an FYI, I converted over to only having a single zone for each camera for now and the motion for the zone fires correctly, and the Person alert in this plugin fires correctly. If I have more than one zone, then motion must be in every zone for the person alert to fire at the camera level. If you have 3 zones and only 2 of them fire for motion/person then the Person alert at the camera level does not fire, but the 2 zone motion alerts fire. If all 3 zones fire for motion, then if a person the Person alert fires at the camera level in this plugin. Have not gotten to looking at all the calls to see why, but I wonder if they are only send a zone alert with person instead of the overall camera until all zones fire for motion. Hmmmm....interesting to say the least.

**Comment by Brandawg93** [comment]
Interesting. This would probably reflect in the network calls as well. I haven't specifically tested this, but I've always found it difficult to trigger person alerts for testing on my cameras (which have multiple zones). Now I know why!
