### ISSUE TITLE
Everything working, including doorbell notifications, but no person, sound or motion alerts

### ISSUE THREAD

**Issue by apnelson13** [Brandawg93/homebridge-nest-cam#372]
**Describe the bug**
I have the motion sensors in HomeKit, as well as the doorbell, video shows fine in HomeKit. I have notifications all set to “on” but I am not getting person or sound notifications, even though I can see the sensor getting triggered for the activities mentioned. I have a nest aware subscription.
**Debug Output**

**To Reproduce**

1. 

**Expected behavior**

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: raspberry pi 3B+
On what iOS version are you having issues: 14.2
What camera types are having issues: nest hello
Does this issue occur consistently or randomly: consistently
If applicable, what was the last version that worked properly: n/a
```

**Comment by Brandawg93** [comment]
Try lowering your `alertCooldownRate ` in the advanced settings in the plugin. Some people didn't like constantly receiving notifications. This was added so notifications only happen every X amount of seconds. Also, while this plugin "works" on a Pi3, it isn't recommended. Many users have complained that the Pi3 cannot handle streaming and notifications on theirs. A Pi4 will dramatically improve the responsiveness of this plugin.

**Comment by apnelson13** [comment]
Thanks, will try that!

**Comment by apnelson13** [comment]
Still no luck, but I’ve confirmed the sensors work with automation. Both the motion and sound sensors trigger the entry light to come on, it’s JUST the banner notification that’s missing. Is it really just pi3 vs 4?

**Comment by Brandawg93** [comment]
If you are able to see the motion sensors trigger in HomeKit, then I don't think it's a problem with your Pi or even the plugin. It sounds like a HomeKit or homebridge issue. You could try updating your homebridge to the latest beta version to see if that fixes the issue. But from a plugin standpoint, if you see the triggers light up, HomeKit should trigger a notification.

**Comment by Brandawg93** [comment]
Also, make sure that notifications are enabled both in the plugin settings and in each camera in HomeKit.

**Comment by apnelson13** [comment]
Thanks, everything seems to be set up right, including all notifications. I will see if I can update to the beta.

**Comment by fretzy99** [comment]
Think I'm having same issue... seems to be working but are receiving generic notifications despite only selecting Person and Motion alerts ... running on pi4, ios14.2, with the nest aware subscription... see homebridge 1.1.6 config below:
![IMG_2533](https://user-images.githubusercontent.com/74735779/101053502-b5d6df80-353c-11eb-9521-d004863f5856.png)
"options": {
                "ffmpegCodec": "libx264",
                "streamQuality": 3,
                "alertCheckRate": 10,
                "alertCooldownRate": 180,
                "alertTypes": [
                    "Person",
                    "Motion"
                ],
                "importantOnly": false,
                "motionDetection": true,
                "streamingSwitch": true,
                "chimeSwitch": true,
                "doorbellAlerts": true,
                "doorbellSwitch": true,
                "audioSwitch": true,
                ]
            },
            "platform": "Nest-cam"

**Comment by Brandawg93** [comment]
@fretzy99 That is intended behavior. HomeKit cannot yet distinguish between different types of events. 

If anyone has anything to add to this, feel free. Otherwise, I will let it close in 3 days.

**Comment by apnelson13** [comment]
Just curious if you had any other thoughts on my original issue. Other than potentially updating to the beta for Homebridge, are there other things I can try to fix my notification issue? Thanks again for your help thus far

**Comment by Brandawg93** [comment]
@apnelson13 When you say that you aren't receiving "person" and "sound" notifications, do you mean that it always just says "motion"? If so, that is intended behavior. Homekit cannot distinguish between event types. It only knows that a motion sensor was triggered.

**Comment by apnelson13** [comment]
No, the motion and sound sensors trigger on HomeKit but I do not receive any banner notifications on my devices. Doorbell alerts work and show up on phone and Apple TV but that’s the only kind of alert. I have no alert type restrictions on the plug-in and have “important alerts only” unchecked.

**Comment by Brandawg93** [comment]
Do you have notifications enabled in both homebridge and HomeKit? In the camera settings on HomeKit, there is a "enable notifications" switch.

Looking at the code, if the sensor is triggered, HomeKit sends a notification if they are enabled.

**Comment by apnelson13** [comment]
Indeed I do, and like I mentioned I get doorbell alerts and alerts for all other devices. Here’s my HomeKit camera settings:



And homebridge plug-in settings

**Comment by Brandawg93** [comment]
If you're getting doorbell alerts properly and all motion settings are on, then it sounds like an issue with HomeKit. I'm not sure how that would be solved. When I test it, it sends the notification correctly every time. You could try asking the community on the discord server to see if anyone else has this issue or has solved it. There is a section for nest-cam users there.

**Comment by apnelson13** [comment]
Thanks Brandon, I will try the community route. Appreciate your time.

**Comment by Brandawg93** [comment]
No problem. Wish I could be of more help, but it's difficult when I can't reproduce the issue. Hopefully someone there may have had the same issue with a fix.

**Comment by fretzy99** [comment]
Sounds good. The nest-cam plugin allows the selection of different alert
types to be notified of and with other homekit native cams this would seem
like a fairly standard notification type for apple to provide/allow. Close
it and if I can get more info I will let you know.

Thanks!
