### ISSUE TITLE
Stuck at Loggin in. Please Wait...

### ISSUE THREAD

**Issue by bobster16** [Brandawg93/homebridge-nest-cam#387]
I've tried installing Nest Cam plugin through Homebridge UI and through SSH (with uninstalls and reboots in between). When trying to log in manually, I am using the same token and cookie from the Nest plugin (which is functional). 

The green bar goes all the way across, but it never moves past "Loggin in. Please wait..."

**Comment by Brandawg93** [comment]
This is a know bug. I will be publishing a fix shortly. Thanks for the heads up!

**Comment by bobster16** [comment]
Thanks for such a quick response. I looked at the other issues from the last couple of days and found one with my exact Title. 

1) I should have looked there first before creating my own issue. Sorry!

2) I manually wrote it into the config.json, and it connected just fine!

**Comment by bobster16** [comment]
@Brandawg93 if it helps at all, the plugin connected and prompted me with Additional Options, but my cameras weren't showing, even after a couple reboots.

I ended up logging out, and then logging in using the automatic way, which didn't work the first round of attempts but did this time. I rebooted again and cameras are now initialized.

**Comment by Brandawg93** [comment]
Fixed in v6.0.3.

**Comment by dallombra** [comment]
Hi, I'm having the same issues. Brand new installations using the latest version of the plugin today.

I receive the 2FA request, but then I'm stuck at "Logging in...please wait"

Any ideas?

**Comment by Brandawg93** [comment]
Use the manual authentication method.

**Comment by dallombra** [comment]
Unfortunately that didn’t work either. Stuck at “finalising”

**Comment by Brandawg93** [comment]
https://github.com/Brandawg93/homebridge-nest-cam/wiki/Manual-Authentication#manually-scraping-the-nest-website
