### ISSUE TITLE
Update Node for myQ now my Nest cam are not showing anymore...no errors reported

### ISSUE THREAD

**Issue by geoffreyspencer** [Brandawg93/homebridge-nest-cam#392]
I had to update the node to upgrade myQ plugin in HomeBridge. Now I have no cameras showing up. I followed the troubleshooting and uninstalled the Nest Cam plugin, restarted Homebridge, re-installed the Nest Cam plug-in, configured the plug-in and restarted the Nest Cam. No errors reported but nothing being reported at all related to Nest Cam is in the log. The plug-in settings do work because I see my email address in the Config window. I am connected to Nest. Just cannot see any of the cameras and is not reporting finding any cameras and yet not reporting any errors either. HomeKit Home app shows nothing for the cameras as if they do not exist.

Any suggestions?

**Comment by Brandawg93** [comment]
Are you using the UI? Try going to Homebridge Settings and clearing the accessory cache for your cameras.

**Comment by geoffreyspencer** [comment]
That was in your troubleshooting list and I did that or at least tried to. None of the Nest Cam accessories was listed in the accessory cache under Homebridge's settings.

**Comment by geoffreyspencer** [comment]
I decided to take a chance and delete ALL my accessories in the cache even though none of the cams were listed in the individual option to delete the accessories. I rebooted and there were all the cams. Weird error. Please mark the problem closed but it has a weird resolution.
