### ISSUE TITLE
How to add automation when Nest hello doorbell is rang?

### ISSUE THREAD

**Issue by hazaart** [Brandawg93/homebridge-nest-cam#393]
I have all options and switches enabled in homebridge. 
I see 3 switches in the home app (chime, audio, streaming) they are all turned on.
When the doorbell is rang there doesn't seem to be any event or switch to hook an automation into.

The documentation howere lists that it shoul be possible
`Receive notifications and set routines for motion or when the doorbell is rang.`

But it doesn't mention how this can be achieved.

Thanks in advance

**Comment by Brandawg93** [comment]
There is a doorbell switch as mentioned in the documentation. It may be hidden within your doorbell camera's settings > accessories section.

**Comment by hazaart** [comment]
Thanks for the swift reply

I currently have the following settings in homebridge:
"motionDetection": false,
"streamingSwitch": false,
"chimeSwitch": false,
"doorbellAlerts": true,
"doorbellSwitch": true,
"audioSwitch": false

The doorbellswitch is set to true yet I'm not able to see any switches. Also not under the camera settings. Although when I open the camera settings it says 'One button is not configured'. I don't see a way how to do it though.

**Comment by Brandawg93** [comment]
Do you see anything under the "camera settings > accessories" tab?

**Comment by hazaart** [comment]
not sure what you mean with accessoires tab

![473E9F37-C534-48E3-B45F-1A5C459167ED](https://user-images.githubusercontent.com/4686079/104186225-6aa2cd00-5416-11eb-9b20-bc04cc0f16a0.jpeg)

**Comment by Brandawg93** [comment]
Weird. Between "Room" and "include in favorites" I have an "accessories" option which is where the button is located. Maybe try clearing your accessory cache in homebridge.

**Comment by hazaart** [comment]
was able to see the tab by setting the other switches back to true. The doorbell is greyed out however.

![DFF3AA62-B14E-4B48-8C02-33F4AFD6722D](https://user-images.githubusercontent.com/4686079/104187585-5069ee80-5418-11eb-805b-1932b4c7f032.jpeg)

**Comment by Brandawg93** [comment]
It's grey until someone presses the doorbell. That's how you are able to setup automations with it.

**Comment by hazaart** [comment]
Got it working now. Thanks for your support!
And thanks for this great plugin. Can now stream the doorbell to the TV when someone rings.

**Comment by cyberralf83** [comment]
Can confirm. Without "indoor chime switch" enabled, the "doorbell switch" will not appear as an accessory. Not sure if this is a bug or how its designed. Either way, any change requires me to "Remove Single Cached Accessory" for it to be reflected in the Home app.
