### ISSUE TITLE
Switch service for Visitor Announcements

### ISSUE THREAD

**Issue by schmittx** [Brandawg93/homebridge-nest-cam#394]
**Is your feature request related to a problem? Please describe.**
In addition to enabling/disabling the indoor chime, I'd also like to disable the "Visitor Announcements" setting (where any Google Assistant-enabled speaker will chime/announce when the doorbell is pressed) during quiet/nap time.

**Describe the solution you'd like**
A switch service to enable/disable the "Visitor Announcements" setting, similar to the existing indoor chime feature.

**Describe alternatives you've considered**
None

**Additional context**
The API lingo is "chime_assist", the property is `doorbell.chime_assist.enabled`.

**Comment by Brandawg93** [comment]
This has been implemented and will be released in the next version (v7). A test version is available if you would like to try it but will require you to login again as the authentication process has been changed dramatically.

**Comment by Brandawg93** [comment]
This will be released soon in v7.
