### ISSUE TITLE
Nest Hello and Nest Hub Max Video appearing in 16:9

### ISSUE THREAD

**Issue by danielmjt** [Brandawg93/homebridge-nest-cam#395]
Hi, video from both my Nest Hello and Nest Hub Max are appearing in 16:9 (stretched) rather than 4:3. I tried deleting the cached cameras and trying again but this did not solve the issue. I’m not sure if it’s a new issue as I’ve been running Homebridge for a few weeks but possible I just never noticed until now.

**Comment by Brandawg93** [comment]
The plugin doesn't actually alter the aspect ratio in any way. Whatever is received from Nest is sent directly through to HomeKit. Note that the snapshots will be in a 16:9 ratio, but the actual stream will be 4:3. This is a Homekit limitation. Looking at my doorbell cam, it is in 4:3 for the stream, but not for the snapshot.

**Comment by danielmjt** [comment]
Strange, I actually have it in 4:3 until I actually click on it, at which point the live stream turns into 16:9. In the Nest app it is 4:3.

**Comment by Brandawg93** [comment]
What does your "options" object look like in your config? I'll try using the same options.

**Comment by danielmjt** [comment]
Thanks:

"options": {
                "ffmpegCodec": "libx264",
                "streamQuality": 2,
                "alertCheckRate": 2,
                "alertCooldownRate": 60,
                "alertTypes": [
                    "Person",
                    "Package Retrieved",
                    "Package Delivered",
                    "Face"
                ],
                "importantOnly": true,
                "motionDetection": true,
                "streamingSwitch": true,
                "chimeSwitch": true,
                "doorbellAlerts": true,
                "doorbellSwitch": true,
                "audioSwitch": true
            },
            "platform": "Nest-cam"
        }

**Comment by danielmjt** [comment]
For what it’s worth, I just tried deleting the plugin entirely together with its config, restarted HomeBridge, checked that the cameras were gone from the Home app, and reinstalled everything from scratch, but the issue was not resolved. Thanks for your help!

**Comment by Brandawg93** [comment]
Interesting...Try setting your `streamQuality` to 3.

**Comment by danielmjt** [comment]
That fixed it, thanks!!

**Comment by danielmjt** [comment]
Seems to be working well at the high quality, I just wanted the stream to load quicker, but I guess in the transcoding it’s changing the aspect ratio for some reason.

**Comment by Brandawg93** [comment]
I think the plugin isn't requesting the correct low-quality stream. I'll fix that in the next release. Thanks for the heads up!

**Comment by danielmjt** [comment]
Thanks!

**Comment by danielmjt** [comment]
And thanks for your work with this plugin!

**Comment by Brandawg93** [comment]
No Problem. Looking around in the Nest code, it seems that Google will force the doorbells and hubs into 16:9 if you ask for a lower stream quality. I assume it helps save bandwidth. Interesting nonetheless. I'm going to keep the code the same but add a notice to the settings page for others.

**Comment by Brandawg93** [comment]
The notice has been added and will be released in v7.
