### ISSUE TITLE
Not been able to generate a valid Refresh Token for Nest Cam Plugin (the Access token acquisition via refresh token failed (code 400))

### ISSUE THREAD

**Issue by CaldenMig21** [Brandawg93/homebridge-nest-cam#400]
**Describe the bug**
I just received the Hoobs and already installed several plugins, but I am having some issues to install the Nest Cam Pluggin.
My Nest Cam is part of a Google Nest Hub, but I can access the camera logging into my nest account, so I am assuming this is not a limitation.

**To Reproduce**
This are the supposed steps to install the pluging:
**Installation**
1. Install this plugin using: npm install -g --unsafe-perm homebridge-nest-cam
2. Add google authentication to config.json
3. Run Homebridge
4. Login with homebridge-config-ui-x or use the manual authentication method.

- The pluging is automaticaly installed in the Hoobs just clicking the install buttom (step 1)
- I don´t see where in the configuration I can add the google authentication (this might be my main issue?) (Step 2)
- The plugins confiruration sección only askedme for a Refresh Token
- I follow the steps to generate a "refresh token" manually (and I did everything in the instructions), but Hoobs have not been able to retrieve the access token
- The only thing I was not able to find where to define the "cookies" in the configuration

**Debug Output**
[Nest-cam] Initializing Nest-cam platform...
9/2/2021 15:41:11 Loading 1 accessories...
9/2/2021 15:41:11 [Nadie en Casa] Initializing DummySwitch accessory...
9/2/2021 15:41:11 [Nadie en Casa] Setting switch to false
9/2/2021 15:41:11 [TuyaWebPlatform] Loading accessory from cache: Luces del balcón 
9/2/2021 15:41:12 Bridge is running on port 51826.
9/2/2021 15:41:12 [Nest-cam] Access token acquisition via refresh token failed (code 400).
9/2/2021 15:41:12 [Nest-cam] Unable to retrieve access token.

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: Hoobs
On what iOS version are you having issues: Windows
What camera types are having issues: Nest Camera in Google Nest Hub
Does this issue occur consistently or randomly: Consistently

**Comment by Brandawg93** [comment]
Take a look at the [manual authentication wiki](https://github.com/Brandawg93/homebridge-nest-cam/wiki/Manual-Authentication). Either method should work for you.

**Comment by CaldenMig21** [comment]
The Plugging only has a field in Hoobs for the "Refresh Token", when I try the Refresh Token method described in manual authentication, I receive the following error: "Access token acquisition via refresh token failed (code 400)." I am running "homebridge-nest-cam login" in the Hoobs Terminal, I follow the seven steps to get a "Refresh Token" and saved the plugging.

The other method: IssueToken and Cookie, can not be typed in the Hoobs UI with this pluggin. Is there a sample config.jason that I should paste to try this method? this plugging is supposed to be Hoobs Certified

**Comment by Brandawg93** [comment]
Try using the browser cookie method and copying the information to your config.json manually. Otherwise, it sounds like you are not putting in the correct value in the form for the refresh token.

**Comment by CaldenMig21** [comment]
Do I need the "apiKey" in this plugging when using the browser cookie method, or just the "IssueToken" and "Cookie"?
A config.json example would be great... thanks for your patience!!!

**Comment by Brandawg93** [comment]
You do not need the apiKey, but many users also use homebridge-nest, so you can simply copy the credentials from there if it's easier for you.

[Example](https://github.com/Brandawg93/homebridge-nest-cam/tree/6dc0f753248fbd6451944bbf59e9e6081dcb13f8#googleauth)

**Comment by LA0068** [comment]
I was successful in loading 7.1 last week with the described manual authentication method.  Today, error 400.  In chrome, I've cleared my cache, used incognito mode...I've tried about 5 times installing/reinstalling the plugin with the same result.  However, today, the "status" column in the attached screen  shows cancelled which I don't remember seeing before.  I am using MACOS with WiFi off.  IP via ethernet.


<img width="1020" alt="Screen Shot 2021-02-18 at 2 48 02 PM" src="https://user-images.githubusercontent.com/79286030/108426461-0800d600-71f9-11eb-9f47-506942b9148a.png">

**Comment by Brandawg93** [comment]
Correct. Copy the request url of the cancelled request into the field in the UI.

**Comment by LA0068** [comment]
I did that several times.  Doubled checked it in the config file.  ..it hasn’t worked this time..error 400.  Last week…worked right away.  But not today.

**Comment by Brandawg93** [comment]
The url is not supposed to be in the config. It is not the refresh token. Also, why would you need to authenticate multiple times? Once should be enough.

**Comment by LA0068** [comment]
This is what I am doing…

Install Nest Cam plugin

Run In terminal window    homebridge-nest-cam login

Open chrome with developer options

Open site
https://accounts.google.com/o/oauth2/v2/auth?nonce=YBEngfJTQj8TWecEaEGRlYf8bWTYQF9tl3B7rtO1wBG&audience=733249279899-spjd3qvje0svjorc6j5lit5m5u8dn32e.apps.googleusercontent.com&response_type=code&code_challenge_method=S256&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fnest-account&code_challenge=mzSRo9MEKkkmY8s4Ofo8sWsybpCJxomsh81KQdqid9I&redirect_uri=com.googleusercontent.apps.733249279899-1gpkq9duqmdp55a7e5lft1pr2smumdla%3A%2Foauth2callback&client_id=733249279899-1gpkq9duqmdp55a7e5lft1pr2smumdla.apps.googleusercontent.com&state=C3LAvAQVxcN3adUascC8xAEuo1lCYjFU0dSpEYE6v5d <https://accounts.google.com/o/oauth2/v2/auth?nonce=YBEngfJTQj8TWecEaEGRlYf8bWTYQF9tl3B7rtO1wBG&audience=733249279899-spjd3qvje0svjorc6j5lit5m5u8dn32e.apps.googleusercontent.com&response_type=code&code_challenge_method=S256&scope=openid%20profile%20email%20https://www.googleapis.com/auth/nest-account&code_challenge=mzSRo9MEKkkmY8s4Ofo8sWsybpCJxomsh81KQdqid9I&redirect_uri=com.googleusercontent.apps.733249279899-1gpkq9duqmdp55a7e5lft1pr2smumdla:/oauth2callback&client_id=733249279899-1gpkq9duqmdp55a7e5lft1pr2smumdla.apps.googleusercontent.com&state=C3LAvAQVxcN3adUascC8xAEuo1lCYjFU0dSpEYE6v5d>

Copy /Paste url into Refresh Token box (numbers hidden)
com.googleusercontent.apps.###########-1gpkq9duqmdp55a7e5lft1pr2smumdla:/oauth2callback?state=C3LAvAQVxcN3adUascC8xAEuo1lCYjFU0dSpEYE6v5d&code=4/0AY0e-g6poSU3SBk9VypGaXRC1MkGTDXQox0B3my-QkSyMy6XHswJMaw0XMI2ucsIr44F8w&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/nest-account&authuser=0&prompt=consent <http://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/nest-account&authuser=0&prompt=consent>

Reboot HOOBs

2/18/2021, 3:37:01 PM [Nest-cam] Access token acquisition via refresh token failed (code 400).
2/18/2021, 3:37:01 PM [Nest-cam] Unable to retrieve access token.

My Nest plugin is working great.

**Comment by Brandawg93** [comment]
If you use the nest plugin, you can simply copy your credentials from it. Nest-cam can use both a refresh token and browser cookies.

**Comment by LA0068** [comment]
Sorry to bother you…

For some reason, it won’t copy the entire URL into the terminal window. 

hoobs@hoobs:/home/hoobs/.hoobs/etc $ homebridge-nest-cam login


7. Copy the entire Request Url (beginning with 'com.googleusercontent.apps') here: com.googleusercontent.apps.733249279899-1gpkq9duqmdp55a7e5lft1pr2smumdla:/oauth2callback?state=C3LAvAQVxcN3adUascC8xAEuo1lCYjFU0dSpEYE6v5d&code=4/0AY0e-g6poSU3SBk9VypGaXRC1MkGTDXQox0B3my-QkSyMy6XHswJMaw0XMI2ucsIr44F8w&scope=email%20profile%20openid%20https://www.googleapis.com/auth/useruthuser=0&prompt=consentww.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/nest-account&a 


Not copied at the end is “uthuser=0&prompt=consent"

********

From the nest plug in, what do I copy and to where?


com.googleusercontent.apps.733249279899-1gpkq9duqmdp55a7e5lft1pr2smumdla:/oauth2callbac=C3LAvAQVxcN3adUascC8xAEuo1lCYjFU0dSpEYE6v5d&code=4/0AY0e-g6poSU3SBk9VypGaXRC1MkGTDXQox0B3my-QkSyMy6XHswJMaw0XMI2ucsIr44F8w&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/nest-account&authuser=0&prompt=consent

**Comment by Brandawg93** [comment]
Not sure why it can't copy the entire string. That sounds like an environment issue. You can copy the entire `googleAuth` object from your nest config section to nest-cam.

**Comment by LA0068** [comment]
WOW…, I can’t believe that Idid that.

Many thanks!
James

**Comment by CaldenMig21** [comment]
James,
Good to know that you did it. Did you found a way to paste the entire URL in the refresh code method? Or did you copied the entire googleAuth object from the nest config section?
Thanks!!

**Comment by LA0068** [comment]
I could not get the entire url to paste for some reason.  So I just copied the nest login into the nest cam.  Worked great.

**Comment by Brandawg93** [comment]
If anyone is still having issues with this, feel free to open a new issue as this one seems to be resolved now.
