### ISSUE TITLE
[Error] This plugin slows down Homebridge

### ISSUE THREAD

**Issue by jamesngob** [Brandawg93/homebridge-nest-cam#402]
1/ I have the Homebridge Nest Cam plugin, worked OK until I updated to version 7.1.0 in the Homebridge U.I version 4.39.1, under the Homebridge v.1.3.1, all recently
It is now throwing the error in the log:

"This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info."

2/ When I click to view the live-view, the camera will not connected, throwing the error

[Nest-cam] [NexusStreamer] Connected
[Nest-cam] [NexusStreamer] Redirecting...
[Nest-cam] [NexusStreamer] Disconnected

And it will loop this error again

3/ And the NEST itself also throws the following error (this error was there before the above ones, but I can still view the live view cam)

[Nest] API observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}

Am I missing anything?
Thank you
**Debug Output**

**To Reproduce**

1. 

**Expected behavior**

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: 
On what iOS version are you having issues: 
What camera types are having issues: 
Does this issue occur consistently or randomly: 
If applicable, what was the last version that worked properly: 
```

**Comment by Brandawg93** [comment]
As far as the "slow to respond", it gives you a url to visit to fix the issue. 

As far as the stream not working, visit the following link and let me know if the first FAQ helps you. 

https://github.com/Brandawg93/homebridge-nest-cam/wiki/FAQ

**Comment by jamesngob** [comment]
@Brandawg93 
I have added the network interface according to your instruction in the FAQ. I did not realize there is an option readily in the homebridge interface. I think I had to use the config file to set that up in the previous homebridge version...
It seems to be smoother and fluidily streaming right now... I will post back in a couple of days...
Thank you again for your continued support. You rock!

**Comment by Brandawg93** [comment]
I've released a new test version (v7.1.1-test.1) that actually resolves the "slow to respond" issue. You can try it out by going to the plugins page, clicking the gear next to the plugin, and selecting "Install Previous Version". Others have reported that it makes their entire homebridge instance faster as well. If you try it out, let me know how it works for you.

**Comment by jamesngob** [comment]
@Brandawg93
I have installed the test version and is running it now... It seems faster overall as you said... I will report back here in the next few hours...

**Comment by Brandawg93** [comment]
v7.1.1 is now live. If you continue to have issues, feel free to reopen this issue.
