### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by soulcook** [Brandawg93/homebridge-nest-cam#404]
Hi. It's me again.

Just wanted to let you know that I've been getting `UnhandledPromiseRejectionWarning` in the logs fairly regularly, and it seems to be associated with nest-cam. Here's a snippet from a log with debug on:

```
[3/1/2021, 2:32:46 PM] [Nest-cam] Checking for alerts on Front Door
[3/1/2021, 2:32:48 PM] [Nest] Current humidity for Z Dressing Room Thermostat is: 46%
[3/1/2021, 2:32:56 PM] [Nest-cam] Checking for alerts on Front Door
(node:286) UnhandledPromiseRejectionWarning: false
(Use `node --trace-warnings ...` to show where the warning was created)
(node:286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)
(node:286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3/1/2021, 2:33:06 PM] [Nest-cam] Checking for alerts on Front Door
[3/1/2021, 2:33:16 PM] [Nest-cam] Checking for alerts on Front Door
```

The warning about Node terminating in this situation in future versions is a bit worrying. I don't know for sure that nest-cam is causing the issue. I only conjecture that it is because it always seems to appear immediately after a nest-cam log message, as above. Unfortunately it doesn't come with a stack trace.

Thought I should let you know. Happy to help if there's more I can do to identify the issue.

**Comment by Brandawg93** [comment]
I see that you have debug output on. Does it only show in debug? My initial guess would be that if it's a Nest-cam issue, it could be that Nest is rate-limiting the alert checks. That should already be handled, but maybe not. You could try running Homebridge with `--trace-warnings` to see where the issue originated.

**Comment by soulcook** [comment]
Hmm. Good question re debug logs. Not sure. Will leave it running for a while with debug off and see if it happens.

If it still occurs I will run Homebridge with `--trace-warnings` as you suggest.

**Comment by Brandawg93** [comment]
I just released v7.1.2. In it, I removed a few async functions that didn't need to be asynchronous. Let me know if that helps any.

**Comment by soulcook** [comment]
Thanks. Have updated, and running very well so far. No issues at all. 🤞

**Comment by Brandawg93** [comment]
Great! If it shows back up, just submit a new issue and I'll take a look.
