### ISSUE TITLE
Need to add documentation for AlertTypes and Zones?

### ISSUE THREAD

**Issue by erikmhauck** [Brandawg93/homebridge-nest-cam#411]
Hello! I am trying to figure out how to only send Alerts when events are detected in a specific Zone.

Briefly looking at the code, this seems possible/supported, but reading the docs I don't see any info on Zones or even AlertTypes for that matter.

So 2 questions:

1. Is this currently supported?
2. If so, how does it work? Should this be added to the readme?

**Comment by Brandawg93** [comment]
Is the `alertType` option what you are looking for?
