### ISSUE TITLE
Need to add documentation for AlertTypes and Zones

### ISSUE THREAD

**Issue by erikmhauck** [Brandawg93/homebridge-nest-cam#412]
**Is your feature request related to a problem? Please describe.**
Hello! I am trying to figure out how to only send Alerts when events are detected in a specific Zone.

Briefly looking at the code, this seems possible/supported, but reading the docs I don't see any info on Zones or even AlertTypes for that matter.

So 2 questions:

Is this currently supported?
If so, how does it work? Should this be added to the readme?

**Describe the solution you'd like**
Add documentation if it is supported

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Brandawg93** [comment]
I commented in the closed thread:

Is the `alertType` option what you are looking for?

**Comment by erikmhauck** [comment]
Yes, but specifically interested in docs surrounding how alertType works with Zones. 

Are neither of these are documented anywhere?

**Comment by Brandawg93** [comment]
Are you using Homebridge or HOOBS? I don't have any extra documentation since the UI in Homebridge automatically generates the zone options for you. 

If not using Homebridge or its UI, the alertType for the zone should be `Zone - ` + the name of the zone as shown on the Nest app.

**Comment by erikmhauck** [comment]
I am using the Homebridge UI. 

So maybe I am actually experiencing a bug then. I have a zone configured in the Nest app but it is not showing up anywhere in the Homebridge UI

**Comment by Brandawg93** [comment]
Yep. Definitely a bug. I'm not seeing my zones either. I'll look into it as soon as I get a chance.

**Comment by erikmhauck** [comment]
Seems to work great! Awesome!

Note: I first had to re-save the plugin settings and reboot after applying the update for the zones to show up.

**Comment by Brandawg93** [comment]
v7.3.0 is now live.

**Comment by mczac** [comment]
alertTypes array in options is used by all Cameras, if you define a zone for a specific camera, it gets populate to all other cameras too. Need a way to select alertTypes per camera.
