### ISSUE TITLE
tvOS notification for motion

### ISSUE THREAD

**Issue by d2ustin** [Brandawg93/homebridge-nest-cam#417]
I’m wanting to know if there is a way you can make the extension trigger a simulated doorbell press if it detects motion in a certain zone.. I know it would require nest aware, but similar to homebridge-ring where motion events can trigger an iOS 14 and tvOS simulated doorbell press, so they it will pop up on appleTV with a screen grab of the camera that triggered said motion.

**Comment by Brandawg93** [comment]
I see the new issue. Closing this.
