### ISSUE TITLE
Option to hide/disable a camera

### ISSUE THREAD

**Issue by khiscott** [Brandawg93/homebridge-nest-cam#420]
It would be great if there was an option to optionally leave out a camera from being bridged into HomeKit.
Say you have three cameras, A, B and C. Then you could:
"options": {
                "hiddenCameras": [
                    "CameraA",
                    "CameraC"
                ],
}
And this would only add Camera B to the Home app.
Thanks!

**Comment by Brandawg93** [comment]
Good suggestion. I'm reopening this.

**Comment by Brandawg93** [comment]
I see your new issue. 👍
