### ISSUE TITLE
Option to hide/disable a camera

### ISSUE THREAD

**Issue by khiscott** [Brandawg93/homebridge-nest-cam#421]
**Is your feature request related to a problem? Please describe.**
I would like a way to leave some of my Nest cameras out of Home app.

**Describe the solution you'd like**
It would be great if there was an setting to optionally leave out a camera from being bridged into HomeKit.
Say you have three cameras, A, B and C. Then you could:
"options": {
"hiddenCameras": [
"CameraA",
"CameraC"
],
}
And this would only add Camera B to the Home app.

**Describe alternatives you've considered**
I don’t think bridged cameras can be deleted in the Home app and checked Homebridge docs but also didn’t see a higher level option.

**Additional context**
Thanks!

**Comment by Brandawg93** [comment]
I've created a new test version (v7.4.0-test.0) with a new config option `cameras` that let's you specify which cameras you would like to see in Homebridge. You can install it via the config-UI. Let me know if this test works for you.

**Comment by khiscott** [comment]
Boom! This looks great and works for me!

**Comment by Brandawg93** [comment]
Thanks for testing! v7.4.0 is now live.
