### ISSUE TITLE
Keep getting 403 error even with new refresh token

### ISSUE THREAD

**Issue by garyhighlinebeta** [Brandawg93/homebridge-nest-cam#424]
**Describe the bug**
Keep getting 403 error even with new refresh token

**Debug Output**
[6/22/2021, 4:46:02 PM] [Nest-cam] Error checking alerts: 403
Troubleshoot here: https://git.io/Jtxww

**To Reproduce**
Followed the instruction with homebridge-nest-cam login. Pasted the refreshToken but still get 403 error.
I have also tried the homebridge-ui update method, same thing.

**Expected behavior**
Expected to connect and not give 403.

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: 
Mac mini
On what iOS version are you having issues: 
iOS 14
What camera types are having issues: 
All camera types
Does this issue occur consistently or randomly: 
consistently
If applicable, what was the last version that worked properly: 
it worked last week ago but stopped working this week. Not sure what changed
```

**Comment by Brandawg93** [comment]
Is this working now? Nest may have been down while you were attempting to authenticate.

**Comment by garyhighlinebeta** [comment]
I still have the same issue.
