### ISSUE TITLE
[Bug]: ERRORError loading plugin "homebridge-nest-cam"

### ISSUE THREAD

**Issue by MalcolmRussell** [Brandawg93/homebridge-nest-cam#428]
### Describe the bug

Since upgrading to HOOBS V4 I cant get the Nest Cam Plugin to work. All that shows in log is

ERROR Error loading plugin "homebridge-nest-cam"

### Debug Output

ERROR Error loading plugin "homebridge-nest-cam"

### Steps to reproduce

1. Install Plugin on HOOBS V4 
2. Start

### Device Type

Raspberry PI

### iOS Version

14

### Camera Types

Indoor, Outdoor and Hello

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
There should be more output than just that. Do you see anything else in the logs?

**Comment by MalcolmRussell** [comment]
![Nest Cam Error](https://user-images.githubusercontent.com/30573745/124757781-da0cfb80-df25-11eb-8bff-6a64a885ac5a.jpg)

**Comment by Brandawg93** [comment]
Is there a way to enable debug output? I haven't tried HOOBS 4 yet and am away from my computer for the holidays.

**Comment by mkellsy** [comment]
Click the Bug Icon on the top of the log.

**Comment by MalcolmRussell** [comment]
The screen shot is taken with Debug Log enabled.

**Comment by mkellsy** [comment]
I have a task to add UI based debugging.
It's coming soon.

**Comment by mkellsy** [comment]
I added the "Enable Debugging" option to the Bridges screen.

You can now enable debugging per bridge from the UI.

![debugging](https://user-images.githubusercontent.com/9777975/124863408-3991f800-df74-11eb-92ef-8f03ca521f13.png)

If the updates don't show up, there is a 4 hour cache to reduce load on our servers. You can go to Menu -> Hub Settings then click Clear Cache. Then you can Check for Updates, and they will show up.

**Comment by MalcolmRussell** [comment]
Updated and  Enabled Debugging on Nest Cam Bridge, log attached(not much in the way of extra info)

![image](https://user-images.githubusercontent.com/30573745/124894516-a2f52380-dfd3-11eb-9f22-54a24f7b41f1.png)

**Comment by mkellsy** [comment]
Try removing the nest cam bridge. Then try reinstalling it.

**Comment by MalcolmRussell** [comment]
Removing bridge and reinstalling results in same error( for me anyway)

**Comment by MalcolmRussell** [comment]
Any suggestions of things to try, I deleted bridge and plug-in cleared chache reinstalled and still no joy. Any idea how to debug further?
