### ISSUE TITLE
[Bug]: Keep getting 403 error even with new refresh token

### ISSUE THREAD

**Issue by garyhighlinebeta** [Brandawg93/homebridge-nest-cam#429]
### Describe the bug

Expected behavior
Expected to connect and not give 403.

### Debug Output

[6/22/2021, 4:46:02 PM] [Nest-cam] Error checking alerts: 403

### Steps to reproduce

Followed the instruction with homebridge-nest-cam login. Pasted the refreshToken but still get 403 error.
I have also tried the homebridge-ui update method, same thing.

### Device Type

mac mini

### iOS Version

any

### Camera Types

any

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
You may be posting an incorrect value in the refreshToken field. Are you using Homebridge or HOOBS?

**Comment by garyhighlinebeta** [comment]
Homebridge. I've reentered a different refreshToken many times

**Comment by Brandawg93** [comment]
Hmmm. Not sure what else could be the issue. 403 means that the refreshToken is incorrect. I've heard of some browsers truncating the text. Have you tried copying it directly to the `config.json`?

**Comment by garyhighlinebeta** [comment]
The plugin has a built in UI to get the token and you press a button to copy it. I dont see how it can go wrong

https://imgur.com/a/iuwoMfP
https://imgur.com/a/3MxRA7q
https://imgur.com/feoKWFH

**Comment by Brandawg93** [comment]
I've heard of some users using older browsers that truncated the refresh token in the UI. But yours looks good to me. Have you tried clearing your homebridge accessory cache just to make sure you aren't seeing a cached accessory?

**Comment by garyhighlinebeta** [comment]
What is the command to clear cache? I googled a bit but someone said the option wont be there in the UI if Im not using hb-service

**Comment by Brandawg93** [comment]
I've only ever used the UI. It's under "Homebridge Settings" for me.

**Comment by garyhighlinebeta** [comment]
Yes as Ive said it is not an option

**Comment by garyhighlinebeta** [comment]
ok I did some more experimenting and it seems to be a vpn problem. The homebridge runs on a mac that has vpn running all the time. Is there a workaround?

**Comment by Brandawg93** [comment]
Homebridge would need to be off of the vpn to connect to other local IOT devices. Does turning the vpn off resolve the 403 errors? I wouldn't think it would interfere with the Google login process, but that's interesting if it does.
