### ISSUE TITLE
FT user getting Error 401[Bug]: 

### ISSUE THREAD

**Issue by schpeen** [Brandawg93/homebridge-nest-cam#437]
### Describe the bug

I am a nest FT tester. I checked the FT box and then I logged into google account and got the token to save into config but its not working I keep getting an error 401. Any help is appreciated. 

### Debug Output

Nest Cam Bridge starting
8/22/2021, 7:17:39 PMNest Cam BridgeLoaded plugin 'homebridge-nest-cam'
8/22/2021, 7:17:39 PMNest Cam BridgeLoading 1 platforms...
8/22/2021, 7:17:40 PMNest Cam BridgeBridge is running on port 51836.
8/22/2021, 7:17:40 PMNest Cam BridgeNest-camERRORAccess token acquisition via refresh token failed (code 401).
8/22/2021, 7:17:40 PMNest Cam BridgeNest-camERRORUnable to retrieve access token.

### Steps to reproduce

1. login to google to get token, save config, getting error 401

### Device Type

raspberry pi

### iOS Version

ios 14

### Camera Types

all nest cameras

### Bug Persistence

Consistently

**Comment by schpeen** [comment]
can someone help me on this. Really would love to get this work.

**Comment by Brandawg93** [comment]
You may want to post in the discord channel. I am not a field tester so I can't troubleshoot issues with it. But there are field testers that monitor the discord.

**Comment by schpeen** [comment]
> You may want to post in the discord channel. I am not a field tester so I can't troubleshoot issues with it. But there are field testers that monitor the discord.

thanks for reply. do you have a link to that group

**Comment by Brandawg93** [comment]
Go to where you created this issue and select the discord option. If you don't see it, it is also in the readme.

**Comment by schpeen** [comment]
thanks...yeah I am not a discord guy its giving me invalid invites or something. its okay i will do more digging online and see what i can find out.

**Comment by Brandawg93** [comment]
There isn't anything on Google for FT users. They kept it pretty secret. Your best bet would be the discord. I just tested the links and they work. You can always try joining the discord from the official Homebridge website. Or you can try asking on Reddit.

**Comment by schpeen** [comment]
Thanks I’ll look into it. As I stated clicking the link and accepting the invitation it keeps saying invite is invalid and I can’t do anything else from
That point.
 Guess I’ll try another way as you suggested. 
 thanks
