### ISSUE TITLE
[Bug]: Home “Favorites” View Snapshot Doesn’t Update

### ISSUE THREAD

**Issue by snoslicer8** [Brandawg93/homebridge-nest-cam#441]
### Describe the bug

What’s happening: When in iOS Home App on favorites screen, Nest Hello camera view doesn’t update snapshot unless I open the livestream view. In this case, the snapshot is replaced with the most recent streamed view.

Expected: The snapshot tile on the favorites screen would previously refresh somewhere between every 10-60 seconds. This stopped happening sometime within the last 7 days.

### Debug Output

There is no output in the Homebridge log connected to Nest Cam unless I open a stream.

### Steps to reproduce

1. Open iOS Home app.
2. Scroll down to favorite cameras.
3. Wait for tile to update (it won’t).
4. Click on tile to open livestream.
5. Close livestream - tile snapshot will update to most recent view on stream.

### Device Type

Mac Mini M1

### iOS Version

15

### Camera Types

Nest Hello Doorbell

### Bug Persistence

Consistently

### Last Working Version

Latest - don’t think there was an update to the plugin that broke this.

**Comment by wild-a** [comment]
I'm having the same issue, however even after I watch the live stream the tile snapshot does not update.
