### ISSUE TITLE
[Bug]: Camera makes excessive dings when trying to talk through it

### ISSUE THREAD

**Issue by cyberpower678** [Brandawg93/homebridge-nest-cam#450]
### Describe the bug

When I attempt to talk through the camera, the talk line keeps opening and closing uncontrollably causing the camera to make incessant dinging noises.

### Debug Output

11/3/2021, 11:16:00 AMNest Cam BridgeWARNINGunhandled rejection: Error: write EPIPE
11/3/2021, 11:18:19 AMNest Cam BridgeNest-cam[NexusStreamer] Connected
11/3/2021, 11:18:19 AMNest Cam BridgeNest-cam[NexusStreamer] Redirecting...
11/3/2021, 11:18:19 AMNest Cam BridgeNest-cam[NexusStreamer] Disconnected
11/3/2021, 11:18:19 AMNest Cam BridgeNest-cam[NexusStreamer] Connected
11/3/2021, 11:18:22 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback Begin
11/3/2021, 11:18:23 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback End
11/3/2021, 11:18:23 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback Begin
11/3/2021, 11:18:24 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback End
11/3/2021, 11:18:25 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback Begin
11/3/2021, 11:18:26 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback End
11/3/2021, 11:18:26 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback Begin
11/3/2021, 11:18:34 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback End
11/3/2021, 11:18:34 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback Begin
11/3/2021, 11:18:36 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback End
11/3/2021, 11:18:36 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback Begin
11/3/2021, 11:18:45 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback End
11/3/2021, 11:18:45 AMNest Cam BridgeNest-cam[NexusStreamer] Talkback Begin

### Steps to reproduce

1. Open a talk line with the Home app

### Device Type

Hoobs Bridge

### iOS Version

15.1

### Camera Types

Nest Outdoor IQ

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
Feel free to reply if this is still an issue.
