### ISSUE TITLE
[Bug]: Nest Cam plugin will not Uninstall

### ISSUE THREAD

**Issue by liudle** [Brandawg93/homebridge-nest-cam#451]
### Describe the bug

I tried to uninstall Nest Cam because it was not allowing me to update the refresh token and it also did not let me link account. When trying to link account, going to the next step after the beginning will lead to a blank dialog screen. Thus, I resulted to trying to uninstall the plugin but the uninstall tool was not successful.

### Debug Output

11:50:16 AMyarn remove v1.22.10
11:50:16 AM[1/3] Removing module homebridge-nest-cam...
11:50:16 AMerror This module isn't specified in a package.json file.
11:50:16 AMinfo Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.

### Steps to reproduce

1. go to the designated pugin (Nest Cam)
2. click "uninstall"
3. select "Hoobs" for the bridge to uninstall from

### Device Type

rasberrypi

### iOS Version

15.0.2

### Camera Types

Google Nest Doorbell Camera

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
You may need to contact [HOOBS support](https://support.hoobs.org/). They would be better suited to help with this.
