### ISSUE TITLE
[Bug]: Cant link account - GUI frozen

### ISSUE THREAD

**Issue by pitboss69** [Brandawg93/homebridge-nest-cam#454]
### Describe the bug

Hi, im clicking on link account. The information pop up appears - I click to proceed and it freezes in a white window with Hoobs/Nest logo.

### Debug Output

30/11/2021, 12:12:15Nest Cam BridgeLoaded plugin 'homebridge-nest'
30/11/2021, 12:12:15Nest Cam BridgeLoaded plugin 'homebridge-nest-cam'
30/11/2021, 12:12:15Nest Cam BridgeLoading 2 platforms...
30/11/2021, 12:12:15Nest Cam BridgeNest-camERRORYou must provide a refreshToken or googleAuth object in config.json. Please see README.md for instructions
30/11/2021, 12:12:15Nest Cam BridgeNestFetching Nest devices.
30/11/2021, 12:12:15Nest Cam BridgeNest-camERRORUnable to retrieve access token.
30/11/2021, 12:12:15Nest Cam BridgeNestERRORYou did not specify your Nest account credentials {'email','password'}, or an access_token, refreshToken, or googleAuth, in config.json
30/11/2021, 12:12:15Nest Cam BridgeNestERRORNOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.
30/11/2021, 12:12:16Nest Cam BridgeBridge is running on port 54826.

### Steps to reproduce

1. 

### Device Type

raspberry Pi hoops

### iOS Version

.

### Camera Types

Nest

### Bug Persistence

Consistently

### Last Working Version

New to this plugin

**Comment by Peltier36** [comment]
I'm having the same issue. Does anyone have a solution?
