### ISSUE TITLE
[Bug]: Snapshot in the Home app does not update

### ISSUE THREAD

**Issue by wild-a** [Brandawg93/homebridge-nest-cam#458]
### Describe the bug

What’s happening: When using the iOS Home app, Nest camera view doesn’t update the snapshot. The snapshot shows a 'now' label even though it is days old. The snapshot view is not replaced with the most recent streamed view either. Opening the livestream view works as expected.

Expected: The snapshot tile on the favorites screen would previously refresh somewhere between every 10-60 seconds. This stopped happening sometime within the last 7 days.

### Debug Output

(node:1411) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
(node:1411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

### Steps to reproduce

1. Steps to reproduce
2. Open iOS Home app.
3. Scroll down to favorite cameras.
4. Wait for tile to update (it won’t).

### Device Type

Raspberry Pi 3

### iOS Version

iOS 15.2

### Camera Types

Nest Cam Indoor

### Bug Persistence

Consistently

**Comment by wild-a** [comment]
Disabling and then enabling the plugin makes it work again.

**Comment by azinman** [comment]
Disabling and re-enabling doesn't work for me. My Nest IQ outdoor cam preview seems current, it's my Nest IQ doorbell that is stale.

**Comment by Brandawg93** [comment]
https://www.macrumors.com/2022/01/05/homekit-camera-thumbnail-issue/

**Comment by wild-a** [comment]
Closing this issue as it appears to be on Apple's side.
