### ISSUE TITLE
[Feature Request]: Access Video Stream 

### ISSUE THREAD

**Issue by barrysmartin** [Brandawg93/homebridge-nest-cam#460]
### Enhancement of issue

I have been looking for a way to expose my Nest camera stream to my Hubitat system via my SharpTools dashboard.  

### Solution

As you have already very eloquently interfaced the Nest API, encoded the stream and stream it into HomeKit, it seems that we should be able to reuse the same RTSP stream coming from your homebridge plugin to stream to Hubitat on demand.

**Comment by Brandawg93** [comment]
I have played around with this and it is relatively simple. I elected not to formally publish this since people could use it to circumvent Google's cloud subscription service. Not sure I want to fight that fight. 😜

**Comment by barrysmartin** [comment]
I have the Nest subscription, but the only way to expose the video stream in SharpTools is with a publicly shared camera URL from Google/Nest.  I would prefer not to expose our cameras to the world and was looking to tap into the functionality that you had already exposed in Homebridge that works so well.

From: Brandon McFarlin ***@***.***>
Date: Wednesday, January 12, 2022 at 9:08 AM
To: Brandawg93/homebridge-nest-cam ***@***.***>
Cc: barrysmartin ***@***.***>, Author ***@***.***>
Subject: Re: [Brandawg93/homebridge-nest-cam] [Feature Request]: Access Video Stream (Issue #460)

I have played around with this and it is relatively simple. I elected not to formally publish this since people could use it to circumvent Google's cloud subscription service. Not sure I want to fight that fight. 😜

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBrandawg93%2Fhomebridge-nest-cam%2Fissues%2F460%23issuecomment-1011081608&data=04%7C01%7C%7C6791d2e90a5c47aefc8608d9d5d4f921%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775932952882619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qbdkgZqfWUFepWiuYSMnCuIFqz4dhtjdewElukMIrxw%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL6KDAN5KTYVWJXOXAJ76KTUVWDM3ANCNFSM5LRKDHDQ&data=04%7C01%7C%7C6791d2e90a5c47aefc8608d9d5d4f921%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775932952882619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VTo9Wa6UULblMCtKJw8FJscVq9yOIOksuHW4nPPnJHQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C6791d2e90a5c47aefc8608d9d5d4f921%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775932952882619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h6JPl8pin8TaAq4mAyy0tQ2q07e0l0N9HqkM1Omksm0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C6791d2e90a5c47aefc8608d9d5d4f921%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775932952882619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=A%2FTRqzqLr3fZexiD%2BaNaTLNqEKdVYKmpjJXX%2FKh9TdA%3D&reserved=0>.

**Comment by Brandawg93** [comment]
When I did it before, I simply copied out the `nest` folder from my plugin and used that in another one. As far as I know, I got it working but couldn't get VLC to be happy with it. And then I started thinking about legal implications.

If you're proficient in coding, it should be fairly simple to copy out the `nest` folder and use it. I would just caution you about making it publicly available.

**Comment by barrysmartin** [comment]
Thank you!

**Comment by Brandawg93** [comment]
Going to close this but feel free to update here if you were able to get it to work!
