### ISSUE TITLE
[Bug]: Nest Cam Thumbnails no longer update

### ISSUE THREAD

**Issue by mikegraben** [Brandawg93/homebridge-nest-cam#461]
### Describe the bug

The plugin works fine - I'm able to see all of my cams in the Home app and view them live.  However, the thumbnails shown on both the Home tab and in individual rooms are stale and refuse to update.

This wasn't previously an issue - it's a new bug.  Everything else appears to work and function as expected.

Also note - this is not an issue in the Home app on MacOS Montery - only on IOS.

### Debug Output

Not seeing any errors/warnings in Homebridge

### Steps to reproduce

1. Open the Home app
2. View Nest Cams on Home tab or individual room
3. Note the thumbnail says 'now' for having been updated, but the thumbnail is old/stale.

### Device Type

Raspberry Pi 3

### iOS Version

15.2.1

### Camera Types

Multiple Nest Cam Outdoor

### Bug Persistence

Consistently

**Comment by valiquette** [comment]
I am having the same issue with multiple cameras, multiple locations. My thumbnails are a month old now. rebooting the phone will show a black screen for some time and then it displays the old image. It always displays as 'now' I never see and 'x S' delay time.

Raspberry PI4b 
Same observation that this seems to by just IOS 15. Homekit on PadOS 15 and Monterey 12 work fine.

**Comment by Brandawg93** [comment]
https://www.macrumors.com/2022/01/05/homekit-camera-thumbnail-issue/

**Comment by valiquette** [comment]
Thanks, I was able to restore the correct behavior by omitting ½ my cameras from the plugin config then repeated the other ½. A few restarts and things seem back to normal.

**Comment by mikegraben** [comment]
Seems to be fixed in IOS 15.3.
