### ISSUE TITLE
[Bug]: setupConnection(host) strips port number from host

### ISSUE THREAD

**Issue by lmcquade** [Brandawg93/homebridge-nest-cam#463]
### Describe the bug

In streamer.js near the top of `setupConnection(host)`, this code strips the port number from `host`:
```
host = host.split(':')[0];
```
I am not sure that this is the correct thing to do.  On my machine, `host` comes in as `oculus5747-us1.dropcam.com:80`.  With the port number stripped, the effective url is `wss://oculus5747-us1.dropcam.com/nexustalk`, which DOES NOT work.   If I comment out this line, the effective url becomes `wss://oculus5747-us1.dropcam.com:80/nexustalk`, which DOES work.   It is odd that Dropcam appears to be using WSS over port 80 instead of 443, but shrug.  Thoughts on removing this line?

### Debug Output

[homebridge-nest-cam] [NexusStreamer] Websocket error: write EPROTO 4726623680:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:ssl/record/rec_layer_s3.c:1544:SSL alert number 42

### Steps to reproduce

1. Get a Nest Hello
2. Open Home application
3. Open Live Video Stream.

### Device Type

MacOS

### iOS Version

N/A

### Camera Types

Nest Hello

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
Hmm. I'm not seeing that code anywhere in the repo. If you look at the [streamer.ts](https://github.com/Brandawg93/homebridge-nest-cam/blob/master/src/nest/streamer.ts) file, I see nothing like that. Are you running the latest version of the plugin?

**Comment by lmcquade** [comment]
Oops.. you are right.  If it is not in the repo, it must have been me.  I have been messing around with that code locally for a couple weeks getting my camera to work.  I'll wipe my plugin and reinstall from scratch.  Sorry for the false alarm.
