### ISSUE TITLE
[Bug]: 403 Error even after re-auth

### ISSUE THREAD

**Issue by checked-wobbles-0p** [Brandawg93/homebridge-nest-cam#468]
### Describe the bug

Getting constant error below. I have uninstalled plug-in and re-auth'd several times but error still persist in log. 

[14/02/2022, 02:50:59] [Nest-cam] Error checking alerts: 403
Troubleshoot here: https://git.io/Jtxww
[14/02/2022, 02:50:59] [Nest-cam] Error checking alerts: 403
Troubleshoot here: https://git.io/Jtxww

### Debug Output

Not sure how to obtain. 

### Steps to reproduce

1. Happens periodically in log, always after restarting Homebridge Server. 

### Device Type

Raspberry Pi 4

### iOS Version

n/a

### Camera Types

Hardwired Nest Camera

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
The latest cameras are not supported.

**Comment by checked-wobbles-0p** [comment]
I don’t have the latest cameras. I have the original nest door bell and the original nest outdoor iq camera.

**Comment by checked-wobbles-0p** [comment]
Yes. And I have gotten a new token several times :-(

**Comment by checked-wobbles-0p** [comment]
> Ah. Whoops. Are you using the refresh token for authentication?

If you will provide instruction, I can get you the debug output if that will help?

**Comment by GrumpyGoslin** [comment]
> I'm getting the same errors with the same setup. Is there a solution? Thanks

Ignore me. As in the FAQ, removing a cached accessory fixed it

**Comment by checked-wobbles-0p** [comment]
> > I'm getting the same errors with the same setup. Is there a solution? Thanks
> 
> Ignore me. As in the FAQ, removing a cached accessory fixed it

I did the same thing, but the error has re-appeared. What about you?
