### ISSUE TITLE
[Bug]: Can not authenticate

### ISSUE THREAD

**Issue by paries** [Brandawg93/homebridge-nest-cam#477]
### Describe the bug

Brand new install of homebridge
All plugins are uptodate 
node v16.14.2
I have installed homebridge-nest v4.6.5 and homebridge-nest-cam v7.5.0

homebridge-nest authenticates fine,   but homebridge-nest-cam I get the error 
[21/03/2022, 22:51:14] [Nest-cam] Nest authentication failed (code undefined).
[21/03/2022, 22:51:14] [Nest-cam] Unable to retrieve access token.

i have used the token that is used in the  homebridge-nest config as well as tried distr/login.js and following the instructions.

the  device is a newer nest door bell.

this is the config

{
    "nest_token": "1//06Tvt*****Q4",
    "options": {
        "ffmpegCodec": "libx264",
        "streamQuality": 3,
        "alertCheckRate": 10,
        "alertCooldownRate": 180,
        "alertTypes": [
            "Motion",
            "Sound",
            "Person",
            "Package Delivered",
            "Package Retrieved",
            "Face",
            "Zone"
        ],
        "importantOnly": true,
        "motionDetection": false,
        "streamingSwitch": true,
        "chimeSwitch": false,
        "announcementsSwitch": false,
        "doorbellAlerts": false,
        "doorbellSwitch": false,
        "audioSwitch": true
    },
    "platform": "Nest-cam"
}

Thanks for any help

### Debug Output

[21/03/2022, 22:51:14] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge A8C3) is running on port 51291.
[21/03/2022, 22:51:14] [Nest-cam] Nest authentication failed (code undefined).
[21/03/2022, 22:51:14] [Nest-cam] Unable to retrieve access token.

### Steps to reproduce

1. install plugin and try to configure with token from distr/login.js

### Device Type

raspberry PI

### iOS Version

latest

### Camera Types

nest doorbell

### Bug Persistence

Consistently

**Comment by ChristoRibeiro** [comment]
Same here. Any update on this @Brandawg93 ?

**Comment by randyparies** [comment]
i bailed and bought https://www.starlinghome.io/
I could not find any answers on how to do it, and these guys have solved it

**Comment by Brandawg93** [comment]
This plugin does not work with the new nest devices yet unfortunately.
