### ISSUE TITLE
Please check

### ISSUE THREAD

**Issue by zzack01** [Brandawg93/homebridge-nest-cam#495]
### Describe the bug

Hello, 

Can you please look over:

https://plugins.hoobs.org/plugin/homebridge-nest-cam

&

https://github.com/Brandawg93/homebridge-nest-cam#readme

Then confirm what information is correct

### Debug Output

.

### Steps to reproduce

1. .

### Device Type

.

### iOS Version

.

### Camera Types

.

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
???

**Comment by zzack01** [comment]
Hello,

Can you check to see what information is correct? I see on the :

https://plugins.hoobs.org/plugin/homebridge-nest-cam

&

https://github.com/Brandawg93/homebridge-nest-cam#readme

they have conflicting issues, can you confirm what is accurate and what
needs to be changed

**Comment by Brandawg93** [comment]
The GitHub is the most accurate information. I'm not sure how often HOOBS updates their site.

**Comment by zzack01** [comment]
Ok thank you

**Comment by zzack01** [comment]
Thank you

**Comment by mkellsy** [comment]
The NPM mirror service stopped. Should be updated now.
