### ISSUE TITLE
[Bug]: The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Shed' was slow to respond

### ISSUE THREAD

**Issue by clw123456** [Brandawg93/homebridge-nest-cam#496]
### Describe the bug

Nest cameras take up to 10 seconds to start showing in Home app. Sometimes don't show at all.

Running Hoobs 4.2.5 and Nest Cam 7.5.1. Performance the same on latest homebridge also. 

Have tried downgrading to 7.5.0 but had same issue.

Logs show an RTP Stream Configuration issue.

### Debug Output

23/06/2022, 15:13:52Nest Camera BridgeNest-cam[NexusStreamer] Connected
23/06/2022, 15:13:52Nest Camera BridgeNest-cam[NexusStreamer] Redirecting...
23/06/2022, 15:13:52Nest Camera BridgeNest-cam[NexusStreamer] Disconnected
23/06/2022, 15:13:53Nest Camera BridgeNest-cam[NexusStreamer] Connected
23/06/2022, 15:13:54Nest Camera BridgeERROR[Nest Camera Bridge 94B7@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Backyard' was slow to respond!

### Steps to reproduce

1. Open Apple Home App
2. Select a camera to stream

### Device Type

Raspberry Pi

### iOS Version

15.5

### Camera Types

Nest IQ Outdoor

### Bug Persistence

Consistently

**Comment by clw123456** [comment]
Don't worry, I gave up and bought a Starling Hub instead. Works very well!

**Comment by Brandawg93** [comment]
No worries. It gets difficult fighting Google on their authentication and implementations so a paid service like Starling is a great solution to get continuous updates and support. I'll be curious to see how long Google allows it to last with Matter becoming available, but it's the most feature complete integration for Nest and HomeKit at the moment.
