### ISSUE TITLE
[Bug]: [homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value.

### ISSUE THREAD

**Issue by starkstrom-de** [Brandawg93/homebridge-nest-cam#502]
### Describe the bug

getting constant message warnings:

[homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://homebridge.io/w/JtMGR for more info.

Looked through wiki and error codes page, cannot find how to address this? 

### Debug Output

N/A

### Steps to reproduce

1. running the plug-in on a raspberry Pi

### Device Type

raspberry pi

### iOS Version

15.x

### Camera Types

Dropcam and NetsCam

### Bug Persistence

Consistently

### Last Working Version

N/a

**Comment by Brandawg93** [comment]
When you look at your camera in the home app under settings, what does it say your camera model is?

**Comment by starkstrom-de** [comment]
One says "Nest Cam Indoor" and the second one is blank.. I think the blank one is the older one, a vintage "Drop Cam".

**Comment by starkstrom-de** [comment]
Hello, installed and the warnings have stopped! Great, thank you! :)

**Comment by demonbane** [comment]
I'm having the same problem, and I suspect it's with the same old original Dropcam model. I tried installing 7.5.2-test.0 but I'm still getting it:

```
[8/12/2022, 3:02:07 PM] Loaded plugin: homebridge-nest-cam@7.5.2-test.0
[8/12/2022, 3:02:07 PM] Registering platform 'homebridge-nest-cam.Nest-cam'
...
[8/12/2022, 3:02:10 PM] [homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise         HomeKit will reject this accessory, ignoring new value. See https://homebridge.io/w/JtMGR for more info.
```
