### ISSUE TITLE
Logs filling with error

### ISSUE THREAD

**Issue by pwlivewire** [Brandawg93/homebridge-nest-cam#508]
### Describe the bug

![09988B90-2A53-41EA-95AE-354BE67A503A](https://user-images.githubusercontent.com/25018910/190925199-3d34641b-77f3-4b3d-a83d-4bac22508217.png)

### Debug Output

Error C hecking alerts: 403
Troubleshoot here: https://git.io/Jtxww

### Steps to reproduce

Unsure

### Device Type

raspberry pi

### iOS Version

16

### Camera Types

4 types

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
403 means your log in credentials have expired. Try logging in again.
