### ISSUE TITLE
[Bug]: AXIOS library version 

### ISSUE THREAD

**Issue by n0rt0nthec4t** [Brandawg93/homebridge-nest-cam#524]
### Describe the bug

package.josn file has a decency for axis >= 0.27.2 version. If this is built with the latest version of axios (1.2.x) this will break json responses back as per https://github.com/axios/axios/issues/5298

Solution is is pin axios version in package.json at 1.1.3 until resolved

### Debug Output

.

### Steps to reproduce

1. 

### Device Type

.

### iOS Version

.

### Camera Types

.

### Bug Persistence

Consistently

### Last Working Version

.

**Comment by Brandawg93** [comment]
I merged your PR and created a new release. Let me know if this works for you. Feel free to reopen if not.

**Comment by Brandawg93** [comment]
Oh. Not your PR 😄 Someone else created a PR to fix this. Let me know if it works for you.
