### ISSUE TITLE
[Bug]: Google oauth2 fails after Google password change

### ISSUE THREAD

**Issue by stulevine** [Brandawg93/homebridge-nest-cam#532]
### Describe the bug

After changing my Google password, the refresh token I was using no long worked (makes sense).  And, when I tried to use the UI to login using Google, and the manual methods mentioned in the wiki,  all methods failed and I received the following response from Google Auth:

```
Access blocked: Nest’s request is invalid

You can’t sign in because Nest sent an invalid request. You can try again later, or contact the [developer](https://github.com/Brandawg93/homebridge-nest-cam/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D%3A+) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Nest, see [error details](https://github.com/Brandawg93/homebridge-nest-cam/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D%3A+).
Error 400: invalid_request

```
See screen shot below.
![A1845E4B-A4FF-4898-B44E-0EF3583A1A07](https://user-images.githubusercontent.com/332119/207606690-aae028e6-5f1b-4880-a3c8-d7f182855061.jpeg)

### Debug Output

Don’t really have any since the url is produced by the login.js file.  It’s just not the correct format or is missing data expected by Google Auth.

### Steps to reproduce

1. Change your google password
2. Attempt to re-authenticate Nest with Google to get the plugin to access your Nest Cams.

### Device Type

Raspberry Pi

### iOS Version

Not an iOS issue

### Camera Types

Nest Cam

### Bug Persistence

Consistently

**Comment by dvltav** [comment]
I have the same issue, but I'm doing new setup.  I've tried the command line:
homebridge-nest-cam login and the GUI, same result.

**Comment by quinnerator** [comment]
Same issue as well

**Comment by mikebrogley** [comment]
Same error, but I had no pwd change. 

As I understand it from the /Homebridge Nest/ plugin docs (at https://github.com/chrisjshull/homebridge-nest#using-a-google-account) the "Refresh Token" auth method is no longer supported server-side by Google: "The refresh token method no longer works due to Google-side changes in October 2022" 

My prior token string was still working until today (23 Dec 2022), but now is not, and as above here the "issue me a new token" URL throws an "Access Blocked" error.

Any chance there's a "Cookies Method" auth patch in work for the Homebridge Nest Cam plugin?

**Comment by quinnerator** [comment]
> Same issue as well

I’ve tried the cookie method and so far, so good for the non nest cam integration.

**Comment by topher-black** [comment]
> I have the same issue, but I'm doing new setup. I've tried the command line: homebridge-nest-cam login and the GUI, same result.

Same situation here with a new setup, Mac Mini Monterey OS.  The UI and terminal command both fail with the same 400 error.

**Comment by 13Hemi** [comment]
Same issue here on a new install

**Comment by cstephe** [comment]
same

**Comment by himerus** [comment]
Getting Nest hooked into Homekit was one of my primary reasons for Homebridge, and this plugin, please advise on this issue!

**Comment by 13Hemi** [comment]
I managed to get it working a different way using the details in [this issue](https://github.com/Brandawg93/homebridge-nest-cam/issues/516)

**Comment by chrisrobert** [comment]
I'm having the same issue. I suspected was due to being in Advanced Protection (and thus not being asked for 2FA codes, instead with a security key). But seems like others with same issue. Appreciate any guidance!

**Comment by chrisrobert** [comment]
I was having this issue and was able to solve it (at least for now) with this code: https://github.com/Brandawg93/homebridge-nest-cam/issues/516#issuecomment-1326679188_

Using the same inputs from the homebridge-nest plugin.

**Comment by jradwan** [comment]
Argh, just ran into this myself today. Off to investigate the suggested links above. :)

**Comment by zuhairmahd** [comment]
So the auth2 is failing on the plugin's settings screen.  Could it be related to Google stopping the use of the [Out Of band auth flow](https://developers.google.com/identity/protocols/oauth2/resources/oob-migratio
n)?
The cookie method definitely does not work for the nest-cam plugin, though strangely enough it works for the nest plugin.
