### ISSUE TITLE
nest accounts no longer supported!

### ISSUE THREAD

**Issue by srob** [Brandawg93/homebridge-nest-cam#65]
Pretty surprised that nest account support has been removed. Installing this update will break many working installations.

Google is not forcing people to migrate to google accounts. Surely a way of testing (via a small group of users wishing to remain on nest accounts) could have been found.

**Comment by Brandawg93** [comment]
How Nest connects to and streams from cameras is very different between Nest accounts and Google accounts. Google is not forcing users to migrate, but they are [strongly encouraging](https://www.macrumors.com/2020/05/05/nest-two-factor-authentication-from-may/) it. This would require users to change their 2FA code in config.json every time they wanted to view their cameras. I asked a few people prior to merging this with the old plugin and was told that it no longer worked for older Nest accounts.

**Comment by srob** [comment]
It absolutely did work with older Nest accounts and the github entry
documented how to get it to work. IMHO your version should have been
maintained as a separate plugin.

Nevertheless, I have decided to break several existing integrations that I
have working with my Nest account and migrate to Google. Homekit
integration is more important to me than these.

And thank you for your active support for this project - I don't want to
takeaway from that but just wish there had been wider consultation before
taking this step.

Best regards,

Simon
