### ISSUE TITLE
Store Nest Videos on NAS/Cloud

### ISSUE THREAD

**Issue by kedaegel** [Brandawg93/homebridge-nest-cam#68]
Would be great if there was a capability to send all Nest cam video files to an ftp or network drive. Or Even just video clips triggered by motion events. Is this the right project for that?

**Comment by Brandawg93** [comment]
For the protection of users, I won't be implementing this. This is similar to Homekit Secure Video where apple will store 10 days of footage for free. This functionality would break Nest's End User License Agreement. I wouldn't want Nest to cancel users' accounts over a feature that I developed.
