### ISSUE TITLE
Error checking alerts: 403

### ISSUE THREAD

**Issue by cgilis** [Brandawg93/homebridge-nest-cam#70]
**Describe the bug**
Got this error in homebridge: Error checking alerts: 403
The Nest Hello is not working anymore.

**To Reproduce**
1. Tried to reboot the Docker container, did not work

**Expected behavior**

**Last Working Version**
homebridge-nest-cam v2.3.4

Include with your bug report this version info:
```
node --v12.16.3
homebridge --1.1.0
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest-cam`

Also include debug log output from startup through seeing the issue:
`homebridge -D`

**Comment by Brandawg93** [comment]
403 means your credentials in config.json are no longer valid. Every so often, Google will invalid them and require you to go through the authentication steps again. Let me know if that fixes your issue.

**Comment by cgilis** [comment]
Thx, will do that!
