### ISSUE TITLE
Alert length vs Cool down 

### ISSUE THREAD

**Issue by valiquette** [Brandawg93/homebridge-nest-cam#78]
**Describe the bug**
Problem configuring homekit automations based on camera motion detected or motion stops detecting events.
The events are not lasting long enough. I would expect the triggered state to remain unchanged during the cool down period. or at least be longer than the check interval.
If current behavior is by design, is it possible to include the alert length in the configuration where it could be user defined.

**To Reproduce**
1. Constant behavior that motion state will revert to false 5 sec after event

**Expected behavior**
Triggered motion events remain true during cool down period

**Last Working Version**
2.1.0 
Was working prior to number of alert fixes for motion. or the addition of the fixed Alert_length
Include with your bug report this version info:
```
node --12.18.0
homebridge --1.1.0
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest-cam`

seems like it may be tied to this section of code
  triggerMotion(accessory: PlatformAccessory): void {
    const self = this; // eslint-disable-line @typescript-eslint/no-this-alias
    this.setMotion(accessory, true);
    this.motionDetected = true;
    setTimeout(async function () {
      self.setMotion(accessory, false);
    }, ALERT_LENGTH);

    setTimeout(async function () {
      self.motionDetected = false;
    }, this.alertCooldown);
  }

**Comment by Brandawg93** [comment]
This is expected behavior. When motion is detected, motion is set to true and a notification is sent to homekit. 5 seconds later, motion is set to false and the cooldown begins, not allowing another notification to be sent for `alertCooldownRate` seconds. Motion must be set to false 5 seconds later or users will begin to receive multiple notifications for the same alert.

**Comment by valiquette** [comment]
The automation is 2 part, I am using is one where motion is detected and I turn a light on, the second is motion is no longer detected and the light is turn off.  it seem like the false is sent so close in time to the true that homekit never turns the light on. If I disable either one of those steps, the step works. But with both on nothing runs. If it did work I am thinking I would see the light on for 5 second every 3 minutes. I am trying to follow what the camera is actually seeing, i am not sure how to do that if it is being set to false prior to the next poll or next update. Any suggestions?

**Comment by Brandawg93** [comment]
I see what mean. I've created a new test version of the plugin that now leaves the motion state on until it doesn't see motion anymore. If you can, try it out and let me know if that works better for you. You can install the test via `npm -g i homebridge-nest-cam@test`.

**Comment by valiquette** [comment]
Yes, the behavior is as I expected, the logic looks better. I also have 2 structures and was able to test that. I'll comment in that thread. Thanks for such a quick turn around.

**Comment by Brandawg93** [comment]
This is now included in v2.5.0. Thanks for the bug report!
