### ISSUE TITLE
Nest Hello adds unconfigured button

### ISSUE THREAD

**Issue by Finch106** [Brandawg93/homebridge-nest-cam#84]
I noticed a few updates ago that having the Nest Hello in your favorites also adds a button. Tapping the button doesn't do anything, but I can't remove it from my favorites without it taking the camera with it. Is there a way to split this up as two different devices, even though the button doesn't do anything?

**Comment by Brandawg93** [comment]
https://github.com/Brandawg93/homebridge-nest-cam#options

Try setting the `doorbellSwitch` to false.

**Comment by novemTeam** [comment]
@Finch106 The button is to assign an action. It represents te doorbell button. With this button you have the option to turn on a light when the doorbell rings

**Comment by Brandawg93** [comment]
I assume this has been resolved. If not, just comment back here.
