### ISSUE TITLE
Discord invite link in README expired

### ISSUE THREAD

**Issue by demonbane** [Brandawg93/homebridge-nest-cam#91]
The invite link for the Discord channel in the README is expired.

**Comment by Brandawg93** [comment]
It seems to be working for me and a few others. I've also confirmed it is still active in discord.

https://discord.com/invite/pc2pqmh

**Comment by demonbane** [comment]
Hmm, not sure what happened there. My browser insists it's expired, but joining directly from the client works just fine. I'm going to assume it's just an issue with my browser then. Closing.
