### ISSUE TITLE
Error checking alerts: 403 - Every 10 seconds

### ISSUE THREAD

**Issue by Rubenfer** [Brandawg93/homebridge-nest-cam#93]
**Describe the bug**

Homebridge log reports the following error every 10 seconds:

`Error checking alerts: 403`

**To Reproduce**
1. Install homebridge-nest-cam v.3.0.1 and configure it

**Expected behavior**

No errors.

**Comment by Brandawg93** [comment]
[Error Codes](https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes)
