### ISSUE TITLE
Hide Audio Streaming Switch from Homekit Option

### ISSUE THREAD

**Issue by mickeyc515** [Brandawg93/homebridge-nest-cam#97]
I’d like the option to suppress the audio streaming switch from being displayed in homekit. I can see a use for some users but personally I don’t like having a switch I could accidentally turn off by saying, “turn of my home” to Siri or toggling it accidentally. Is this something that could be optionally suppressed?

**Comment by Brandawg93** [comment]
This is enabled in v3.2.0. You can set the `audioSwitch` option to false to disable it.

**Comment by mickeyc515** [comment]
Thank you - I did a quick search and didn’t see an option. Thanks!
